export const dynamic="force-dynamic";
import { and, eq } from "drizzle-orm";
import { z } from "zod";
import { created, fail, handleApiError } from "@/lib/api";
import { hasStoreAccess, requireAuth } from "@/lib/auth";
import { aiActionProposals, aiLogs, categories, db, products } from "@/lib/db";
import { getMerchantPrimaryStore } from "@/lib/db/queries";
import { generateProductCopy } from "@/lib/enterprise/merchant-ai";
import { generateAiText } from "@/lib/ai/gateway";
import { userHasStoreOperation } from "@/lib/rbac";
const schema=z.object({productId:z.string().uuid(),tone:z.enum(["professional","luxury","friendly","urgent"]).default("professional"),audience:z.string().trim().max(180).optional().nullable(),features:z.string().trim().max(1200).optional().nullable()});
export async function POST(request:Request){try{const session=await requireAuth();const store=await getMerchantPrimaryStore(session.userId);if(!store||!hasStoreAccess(session,store.id))return fail("لا يوجد متجر متاح",403);if(!(await userHasStoreOperation(session.userId,store.id,"ai.use")))return fail("لا تملك صلاحية استخدام ذكاء المتجر",403);const payload=schema.parse(await request.json());const [product]=await db.select({product:products,categoryName:categories.name}).from(products).leftJoin(categories,eq(products.categoryId,categories.id)).where(and(eq(products.id,payload.productId),eq(products.storeId,store.id))).limit(1);if(!product)return fail("المنتج غير موجود",404);const copy=generateProductCopy({baseName:product.product.name,category:product.categoryName||undefined,features:payload.features||product.product.shortDescription||undefined,audience:payload.audience||undefined,tone:payload.tone});const external=await generateAiText({system:"أنت محرر محتوى منتجات عربي. لا تذكر ادعاءات غير موجودة ولا تعد بسعر أو مخزون.",prompt:`حسن صياغة هذا المنتج فقط: ${JSON.stringify({name:product.product.name,category:product.categoryName,features:payload.features||product.product.shortDescription||"",tone:payload.tone})}`,fallback:`عنوان مقترح: ${copy.productName}\nوصف: ${copy.description}`});const expiresAt=new Date(Date.now()+24*60*60*1000);const [proposal]=await db.transaction(async tx=>{await tx.insert(aiLogs).values({storeId:store.id,userId:session.userId,role:"assistant",prompt:`product_copy:${product.product.id}`,response:external.text,metadata:{provider:external.provider,external:external.external,safetyMode:"approval_required"}});return tx.insert(aiActionProposals).values({userId:session.userId,storeId:store.id,audience:"merchant",taskType:"product_copy",title:`تحسين محتوى: ${product.product.name}`,description:"مسودة عنوان ووصف وكلمات مفتاحية. لن تغير السعر أو المخزون أو حالة النشر.",actionType:"apply_product_copy",payload:{productId:product.product.id,storeId:store.id,fields:{name:copy.productName,shortDescription:copy.metaDescription,description:copy.description,specifications:{...(product.product.specifications||{}),aiKeywords:copy.keywords.join("، ")},aiNarrative:external.text},original:{name:product.product.name,shortDescription:product.product.shortDescription,description:product.product.description}},riskLevel:"low",status:"pending_approval",provider:external.provider,model:external.model,expiresAt}).returning();});return created({proposal,preview:copy,narrative:external.text,message:"تم إنشاء مسودة AI. راجعها ثم اعتمدها لتطبيق المحتوى فقط."});}catch(error){return handleApiError(error,"تعذر إنشاء مسودة محتوى المنتج");}}
