"use client";

import { FormEvent, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { apiClient, ApiClientError } from "@/lib/client/api-client";

type RequestRow = any;
type Connector = { id: string; provider: string; displayName: string; version: string; systemType: string; connectionModes: string[]; agentPackageUrl: string | null; documentationUrl: string | null; status: string };
const statusLabel: Record<string, string> = { pending_review: "بانتظار مراجعة الإدارة", under_review: "قيد المراجعة", needs_information: "مطلوب معلومات إضافية", approved_for_setup: "معتمد للإعداد", agent_connected: "تم اتصال Agent", mapping_in_progress: "ربط الأصناف قيد التنفيذ", ready_for_certification: "جاهز للشهادة", activated: "تم تفعيل ERP Mode", rejected: "مرفوض", cancelled: "ملغي" };
function statusVariant(status: string) { return status === "activated" ? "success" as const : status === "rejected" ? "danger" as const : "warning" as const; }

export function ErpIntegrationRequestPanel({ initial }: { initial: { requests: RequestRow[]; connectors: Connector[] } }) {
  const router = useRouter(); const [message, setMessage] = useState<string | null>(null); const [loading, setLoading] = useState(false);
  const activeRequest = useMemo(() => initial.requests.find((row) => !["activated", "rejected", "cancelled"].includes(row.request.status)), [initial.requests]);
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const form = new FormData(event.currentTarget); setLoading(true); setMessage(null);
    try {
      const data = await apiClient.post<any>("/api/merchant/erp-integration-requests", {
        provider: form.get("provider"), erpVersion: form.get("erpVersion") || null, erpType: form.get("erpType"), connectionMethod: form.get("connectionMethod"), branchCount: Number(form.get("branchCount") || 0), warehouseCount: Number(form.get("warehouseCount") || 0), businessActivity: form.get("businessActivity") || null, operationsVolume: form.get("operationsVolume"),
        technicalContact: { name: form.get("contactName") || undefined, phone: form.get("contactPhone") || undefined, email: form.get("contactEmail") || undefined, role: form.get("contactRole") || undefined },
        readiness: { hasTechnicalSupport: form.get("hasTechnicalSupport") === "on", hasDatabaseBackup: form.get("hasDatabaseBackup") === "on", canInstallAgent: form.get("canInstallAgent") === "on", canCreateStagingTables: form.get("canCreateStagingTables") === "on", notes: form.get("readinessNotes") || undefined }, merchantNote: form.get("merchantNote") || null
      }, { invalidateTags: ["merchant:erp-requests"] });
      setMessage(data.message || "تم إرسال الطلب"); event.currentTarget.reset(); router.refresh();
    } catch (caught) { setMessage(caught instanceof ApiClientError ? caught.message : "تعذر إرسال الطلب"); } finally { setLoading(false); }
  }
  return <div className="space-y-8">{message ? <p className="rounded-2xl border bg-white p-4 text-sm font-bold text-slate-700">{message}</p> : null}<section className="rounded-3xl border border-blue-100 bg-blue-50 p-5"><h2 className="text-xl font-black text-blue-950">كيف يتم ربط نظامك؟</h2><ol className="mt-3 grid gap-2 text-sm font-bold leading-7 text-blue-900 md:grid-cols-2"><li>1. أرسل نوع نظامك وطريقة الاتصال.</li><li>2. تراجع الإدارة الجاهزية وتعين موصلاً مناسباً.</li><li>3. تحصل من الدعم على Integration Key مرة واحدة.</li><li>4. يثبت الفني Agent أو يجهز API/ملفات الاستيراد.</li><li>5. يتم ربط External IDs والمخازن والفروع.</li><li>6. بعد الشهادة فقط يفتح ERP Mode للمخزون والفواتير.</li></ol></section>
    {activeRequest ? <RequestStatus requestRow={activeRequest} /> : <form onSubmit={submit} className="grid gap-4 rounded-3xl border bg-white p-6 shadow-card md:grid-cols-2"><div className="md:col-span-2"><h2 className="text-xl font-black">طلب تفعيل ربط ERP</h2><p className="mt-1 text-xs leading-6 text-slate-500">لا تدخل كلمة مرور ERP أو Connection String أو API Key هنا. هذه البيانات تبقى على جهاز التاجر أو داخل مدير الأسرار المعتمد.</p></div><Field label="اسم النظام المحاسبي / ERP" name="provider" required placeholder="مثال: Onyx Pro، محاسبي، نظام محلي خاص"/><Field label="نسخة النظام" name="erpVersion" placeholder="مثال: 2025"/><Select label="نوع النظام" name="erpType" values={[["desktop", "Desktop ERP"], ["cloud", "Cloud ERP"], ["sql_server", "SQL Server محلي"], ["access", "Microsoft Access"], ["pos", "POS"], ["custom", "نظام مخصص"]]} /><Select label="طريقة الاتصال" name="connectionMethod" values={[["local_agent", "Local Sync Agent (موصى به للنظم المكتبية)"], ["cloud_api", "Cloud / REST API"], ["file_exchange", "CSV / Excel Exchange"], ["manual_export", "تصدير يدوي مؤقت"], ["custom", "طريقة مخصصة"]]} /><Field label="عدد الفروع" name="branchCount" type="number" defaultValue="0"/><Field label="عدد المخازن" name="warehouseCount" type="number" defaultValue="0"/><Field label="نوع النشاط" name="businessActivity" placeholder="مثال: إلكترونيات / مواد غذائية"/><Select label="حجم العمليات" name="operationsVolume" values={[["low", "منخفض"], ["medium", "متوسط"], ["high", "مرتفع"], ["enterprise", "كبير/Enterprise"]]} /><div className="md:col-span-2 rounded-2xl bg-slate-50 p-4"><h3 className="font-black">جهة الاتصال الفنية</h3><div className="mt-3 grid gap-3 md:grid-cols-2"><Field label="الاسم" name="contactName"/><Field label="الدور" name="contactRole" placeholder="محاسب / مسؤول IT"/><Field label="الهاتف" name="contactPhone"/><Field label="البريد الإلكتروني" name="contactEmail" type="email"/></div></div><div className="md:col-span-2 rounded-2xl bg-slate-50 p-4"><h3 className="font-black">جاهزية النظام</h3><div className="mt-3 grid gap-2 md:grid-cols-2 text-sm font-bold"><Check name="hasTechnicalSupport" label="يتوفر دعم فني للنظام"/><Check name="hasDatabaseBackup" label="توجد نسخة احتياطية حديثة"/><Check name="canInstallAgent" label="يمكن تثبيت Agent على جهاز النظام"/><Check name="canCreateStagingTables" label="يمكن إنشاء staging/import tables أو مجلد ملفات"/></div><div className="mt-3"><Label>ملاحظات الجاهزية</Label><Textarea name="readinessNotes" className="mt-2" /></div></div><div className="space-y-2 md:col-span-2"><Label>ملاحظة للإدارة</Label><Textarea name="merchantNote" placeholder="اذكر أي متطلبات خاصة أو موعد مناسب للتواصل" /></div><Button disabled={loading} className="md:col-span-2">إرسال طلب تفعيل الربط</Button></form>}
    {initial.requests.filter((row) => row !== activeRequest).length ? <section className="rounded-3xl border bg-white p-6 shadow-card"><h2 className="text-xl font-black">سجل طلبات الربط</h2><div className="mt-4 space-y-3">{initial.requests.filter((row) => row !== activeRequest).map((row) => <RequestStatus key={row.request.id} requestRow={row} compact />)}</div></section> : null}
  </div>;
}
function RequestStatus({ requestRow, compact = false }: { requestRow: RequestRow; compact?: boolean }) { const request=requestRow.request; const connector=requestRow.connector; return <article className="rounded-3xl border bg-white p-5 shadow-card"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-black text-slate-950">{request.requestNumber} — {request.provider}</h3><p className="mt-1 text-xs font-bold text-slate-500">{request.erpType} · {request.connectionMethod} · فروع {request.branchCount} · مخازن {request.warehouseCount}</p></div><Badge variant={statusVariant(request.status)}>{statusLabel[request.status] || request.status}</Badge></div>{!compact ? <div className="mt-4 grid gap-2 text-xs md:grid-cols-4"><Stat label="Mapped Products" value={request.mappingSummary?.mappedProducts || 0}/><Stat label="Unmapped" value={request.mappingSummary?.unmappedProducts ?? "-"}/><Stat label="Warehouses" value={request.mappingSummary?.warehouses || request.warehouseCount}/><Stat label="Branches" value={request.mappingSummary?.branches || request.branchCount}/></div> : null}{request.adminNote ? <p className="mt-3 rounded-xl bg-amber-50 p-3 text-sm font-bold text-amber-800">ملاحظة الإدارة: {request.adminNote}</p> : null}{connector ? <div className="mt-3 rounded-xl bg-blue-50 p-3 text-xs font-bold text-blue-800">الموصل المعين: {connector.displayName} v{connector.version}{connector.documentationUrl ? <a className="mr-2 underline" href={connector.documentationUrl} target="_blank">دليل الإعداد</a> : null}<Link className="mr-2 underline font-black text-amber-700" href="/merchant/integrations/setup">تحميل حزمة الـ SQL و appsettings.json الجاهزة</Link>{connector.agentPackageUrl ? <a className="mr-2 underline" href={connector.agentPackageUrl} target="_blank">تنزيل الحزمة المعتمدة</a> : <span className="mr-2 text-slate-500">لا توجد حزمة Agent موقعة متاحة بعد؛ ينسق الدعم الفني التثبيت التجريبي.</span>}</div> : null}</article> }
function Field({ label, name, type="text", required=false, placeholder, defaultValue }: { label:string; name:string; type?:string; required?:boolean; placeholder?:string; defaultValue?:string }) { return <label className="space-y-2 text-sm font-black text-slate-700"><span>{label}</span><Input name={name} type={type} required={required} placeholder={placeholder} defaultValue={defaultValue}/></label> }
function Select({label,name,values}:{label:string;name:string;values:Array<[string,string]>}){return <label className="space-y-2 text-sm font-black text-slate-700"><span>{label}</span><select name={name} className="h-11 w-full rounded-xl border bg-white px-3 text-sm">{values.map(([value,text])=><option key={value} value={value}>{text}</option>)}</select></label>}
function Check({name,label}:{name:string;label:string}){return <label className="flex items-center gap-2"><input name={name} type="checkbox"/>{label}</label>}
function Stat({label,value}:{label:string;value:string|number}){return <div className="rounded-xl bg-slate-50 p-3"><span className="text-slate-500">{label}</span><b className="mt-1 block text-slate-950">{value}</b></div>}
