"use client";

import { useState, type FormEvent } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { formatCurrency } from "@/lib/utils";
import { providerLabel } from "@/lib/payments/methods";

type Payment = { id: string; storeId: string | null; name: string; code: string; provider: string; description: string | null; isActive: boolean; sortOrder: number; financialProviderId?: string | null };
type FinancialProvider = { id: string; name: string; slug: string; type: string; status: string; currencyCode: string; supportsCOD: boolean; supportsDeposits: boolean; supportsWithdrawals: boolean; supportsRefunds: boolean };
type Shipping = { id: string; storeId: string | null; name: string; code: string; fee: string; description: string | null; estimatedDaysMin: number; estimatedDaysMax: number; isActive: boolean; sortOrder: number; coverageConfig?: Record<string, unknown> };
type Governorate = { id: string; name: string };
type OrderSettings = { autoAcceptOrders: boolean; allowCancellation: boolean; cancellationHours: number; minOrderAmount: number; preparationMinutes: number; enableReservationExpiry?: boolean; reservationExpiryMinutes?: number; returnPolicy: string; shippingPolicy: string; notes: string };
type IntegrationSettings = { integrationEnabled: boolean; integrationMode: "ERP" | "STANDALONE"; erpProvider: string; erpAccess?: "admin_enabled" | "disabled"; inventoryAuthority?: string; invoiceAuthority?: string; accountingRevenueAuthority?: string; settlementAuthority?: string; priceAuthority?: string; productDataAuthority?: string; bankAccountsAuthority?: string; customerDataAuthority?: string };
type OperationSettings = { operationStatus: string; operationNote?: string | null; businessHours?: Record<string, unknown> };

export function OperationsSettingsPanel({ storeId, payments, shippings, financialProviders, governorates, orderSettings, integrationSettings, operationSettings }: { storeId: string; payments: Payment[]; shippings: Shipping[]; financialProviders: FinancialProvider[]; governorates: Governorate[]; orderSettings: OrderSettings; integrationSettings: IntegrationSettings; operationSettings: OperationSettings }) {
  const router = useRouter();
  const [message, setMessage] = useState<string | null>(null);
  const [selectedFinancialProviderId, setSelectedFinancialProviderId] = useState(financialProviders[0]?.id || "");
  const selectedFinancialProvider = financialProviders.find((provider) => provider.id === selectedFinancialProviderId);
  const paymentProvider = selectedFinancialProvider?.type === "cod" ? "cod" : selectedFinancialProvider?.type === "bank" ? "bank_transfer" : selectedFinancialProvider?.type === "wallet" ? "wallet" : selectedFinancialProvider?.type === "hawala" ? "remittance" : selectedFinancialProvider?.type === "gateway" ? "local_gateway" : "manual";

  async function post(endpoint: string, payload: Record<string, unknown>, form?: HTMLFormElement) {
    const response = await fetch(endpoint, { method: endpoint.includes("order-settings") || endpoint.includes("integration-settings") || endpoint.includes("store-operation") ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ storeId, ...payload }) });
    const json = await response.json();
    setMessage(response.ok ? `✓ ${json.data?.message || json.message || "تم الحفظ"}` : json.message || "تعذر الحفظ");
    if (response.ok) { form?.reset(); router.refresh(); }
  }
  async function remove(endpoint: string) { if(!window.confirm("هل تريد حذف هذا العنصر؟")) return; const response=await fetch(endpoint,{method:"DELETE"}); const json=await response.json().catch(()=>({})); setMessage(response.ok?"✓ تم الحذف":json.message||"تعذر الحذف"); if(response.ok) router.refresh(); }

  function addPayment(e: FormEvent<HTMLFormElement>) {
    e.preventDefault();
    const formElement = e.currentTarget;
    const f = new FormData(formElement);
    const config = {
      accountName: f.get("accountName") || undefined,
      bankName: f.get("bankName") || undefined,
      accountNumber: f.get("accountNumber") || undefined,
      iban: f.get("iban") || undefined,
      walletName: f.get("walletName") || undefined,
      walletNumber: f.get("walletNumber") || undefined,
      exchangeCompany: f.get("exchangeCompany") || undefined,
      recipientName: f.get("recipientName") || undefined,
      recipientPhone: f.get("recipientPhone") || undefined,
      instructions: f.get("instructions") || undefined,
      requiresProof: f.get("requiresProof") === "on"
    };
    post("/api/merchant/payment-methods", { financialProviderId: f.get("financialProviderId"), name: f.get("name") || selectedFinancialProvider?.name, code: f.get("code") || undefined, description: f.get("description") || undefined, config, isActive: true }, formElement);
  }
  function addShipping(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const formElement=e.currentTarget; const f=new FormData(formElement); const mode=String(f.get("coverageMode")||"all_yemen"); const coverageConfig={ mode, governorateIds:f.getAll("governorateIds").map(String).filter(Boolean), feeOverrides:[], freeShippingThreshold:f.get("freeShippingThreshold")?Number(f.get("freeShippingThreshold")):null, codEnabled:true, pickupAddress:f.get("pickupAddress")||null, courierName:f.get("courierName")||null, courierPhone:f.get("courierPhone")||null, customerInstructions:f.get("customerInstructions")||null }; post("/api/merchant/shipping-methods", { name:f.get("name"), code:f.get("code")||undefined, fee:Number(f.get("fee")||0), estimatedDaysMin:Number(f.get("estimatedDaysMin")||1), estimatedDaysMax:Number(f.get("estimatedDaysMax")||3), description:f.get("description")||undefined, coverageConfig, isActive:true }, e.currentTarget); }
  function saveOrders(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const formElement=e.currentTarget;const f=new FormData(formElement); post("/api/merchant/order-settings", { autoAcceptOrders:f.get("autoAcceptOrders")==="on", allowCancellation:f.get("allowCancellation")==="on", cancellationHours:Number(f.get("cancellationHours")||0), minOrderAmount:Number(f.get("minOrderAmount")||0), preparationMinutes:Number(f.get("preparationMinutes")||0), enableReservationExpiry:f.get("enableReservationExpiry")==="on", reservationExpiryMinutes:Number(f.get("reservationExpiryMinutes")||120), returnPolicy:f.get("returnPolicy")||"", shippingPolicy:f.get("shippingPolicy")||"", notes:f.get("notes")||"" }); }
  function saveIntegration(e: FormEvent<HTMLFormElement>) { e.preventDefault(); post("/api/merchant/integration-settings", { integrationEnabled:false, integrationMode:"STANDALONE", erpProvider:"none" }); }
  function saveOperation(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const f=new FormData(e.currentTarget); let businessHours: Record<string, unknown> = {}; try { businessHours = JSON.parse(String(f.get("businessHours") || "{}")); } catch { setMessage("صيغة أوقات الدوام يجب أن تكون JSON صحيح"); return; } post("/api/merchant/store-operation", { operationStatus:f.get("operationStatus")||"OPEN", operationNote:f.get("operationNote")||"", businessHours }); }

  return <div className="space-y-8">
    {message ? <div className="rounded-2xl border bg-white p-4 text-sm font-bold text-slate-700 shadow-card">{message}</div> : null}
    <div className="grid gap-8 xl:grid-cols-2">
      <section className="rounded-3xl border bg-white p-6 shadow-card">
        <h2 className="mb-4 text-xl font-black">وسائل الدفع داخل المتجر</h2>
        <form onSubmit={addPayment} className="grid gap-3 md:grid-cols-2">
          <Field label="الاسم" name="name" required />
          <Field label="الكود" name="code" />
          <div className="space-y-2"><Label>المزود المعتمد</Label><select name="financialProviderId" value={selectedFinancialProviderId} onChange={(e)=>setSelectedFinancialProviderId(e.target.value)} required className="h-11 w-full rounded-xl border bg-white px-4 text-sm"><option value="">اختر مزوداً معتمداً</option>{financialProviders.map((provider)=><option key={provider.id} value={provider.id}>{provider.name} — {provider.type}</option>)}</select></div>
          <Field label="اسم الحساب/المستفيد" name="accountName" />
          {paymentProvider === "bank_transfer" ? <><Field label="اسم البنك" name="bankName" /><Field label="رقم الحساب" name="accountNumber" /><Field label="IBAN" name="iban" /></> : null}
          {paymentProvider === "wallet" ? <><Field label="اسم المحفظة" name="walletName" placeholder="مثال: جوالي / STC Pay" /><Field label="رقم المحفظة" name="walletNumber" /></> : null}
          {paymentProvider === "remittance" ? <><Field label="شركة الصرافة" name="exchangeCompany" placeholder="مثال: الكريمي" /><Field label="اسم المستلم" name="recipientName" /><Field label="هاتف المستلم" name="recipientPhone" /></> : null}
          <label className="flex items-center gap-2 rounded-2xl bg-slate-50 px-4 text-sm font-bold"><input name="requiresProof" type="checkbox" defaultChecked={paymentProvider !== "cod"}/> يتطلب إثبات دفع</label>
          <div className="space-y-2 md:col-span-2"><Label>تعليمات الدفع للعميل</Label><Textarea name="instructions" placeholder="اكتب تعليمات واضحة: رقم الحساب، اسم المستلم، ملاحظات التحويل..." /></div>
          <div className="space-y-2 md:col-span-2"><Label>الوصف الداخلي</Label><Textarea name="description" /></div>
          <Button className="md:col-span-2">إضافة وسيلة دفع</Button>
        </form>
        <List items={payments} render={(p)=><div><div className="flex items-center justify-between"><b>{p.name}</b><Badge variant={p.isActive?"success":"outline"}>{p.storeId?"خاص بالمتجر":"عام"}</Badge></div><p className="text-xs text-slate-500">{p.code} — {providerLabel(p.provider)}</p>{p.storeId?<Button size="sm" variant="destructive" className="mt-2" onClick={()=>remove(`/api/merchant/payment-methods/${p.id}`)}>إيقاف التعامل</Button>:null}</div>}/>
      </section>
      <section className="rounded-3xl border bg-white p-6 shadow-card"><h2 className="mb-2 text-xl font-black">وسائل الشحن داخل المتجر</h2><p className="mb-4 text-xs font-bold leading-6 text-slate-500">التاجر يستلم النقد عند التسليم. اختر المناطق التي تغطيها لتظهر هذه الوسيلة فقط للعملاء المناسبين.</p><form onSubmit={addShipping} className="grid gap-3 md:grid-cols-2"><Field label="الاسم" name="name" required/><Field label="الكود" name="code"/><Field label="رسوم الشحن الأساسية" name="fee" type="number"/><Field label="أقل مدة بالأيام" name="estimatedDaysMin" type="number"/><Field label="أقصى مدة بالأيام" name="estimatedDaysMax" type="number"/><div className="space-y-2"><Label>نطاق التغطية</Label><select name="coverageMode" defaultValue="all_yemen" className="h-11 w-full rounded-xl border bg-white px-4 text-sm"><option value="all_yemen">كل محافظات اليمن</option><option value="selected_governorates">محافظات محددة</option><option value="pickup_only">استلام من المتجر فقط</option></select></div><div className="space-y-2 md:col-span-2"><Label>المحافظات المغطاة عند اختيار «محافظات محددة»</Label><select name="governorateIds" multiple className="min-h-28 w-full rounded-xl border bg-white p-3 text-sm">{governorates.map((item)=><option key={item.id} value={item.id}>{item.name}</option>)}</select></div><Field label="شحن مجاني عند مبلغ" name="freeShippingThreshold" type="number" placeholder="اختياري"/><Field label="اسم المندوب/شركة التوصيل" name="courierName"/><Field label="هاتف المندوب/الشحن" name="courierPhone"/><Field label="عنوان الاستلام من المتجر" name="pickupAddress" placeholder="مطلوب لخيار الاستلام"/><div className="space-y-2 md:col-span-2"><Label>تعليمات تظهر للعميل</Label><Textarea name="customerInstructions" placeholder="مثال: سيؤكد المتجر وقت التسليم بالاتصال، والدفع نقداً عند الاستلام."/></div><div className="space-y-2 md:col-span-2"><Label>الوصف الداخلي</Label><Textarea name="description"/></div><Button className="md:col-span-2">إضافة وسيلة شحن</Button></form><List items={shippings} render={(s)=><div><div className="flex items-center justify-between"><b>{s.name}</b><Badge variant={s.isActive?"success":"outline"}>{s.storeId?"خاص بالمتجر":"عام"}</Badge></div><p className="text-xs text-slate-500">{s.code} — {formatCurrency(s.fee)} — {s.estimatedDaysMin}-{s.estimatedDaysMax} يوم</p><p className="mt-1 text-xs font-bold text-blue-700">النطاق: {String(s.coverageConfig?.mode || "all_yemen")}</p>{s.storeId?<Button size="sm" variant="destructive" className="mt-2" onClick={()=>remove(`/api/merchant/shipping-methods/${s.id}`)}>حذف</Button>:null}</div>}/></section>
    </div>
    <section className="rounded-3xl border bg-white p-6 shadow-card"><h2 className="mb-4 text-xl font-black">حالة تشغيل المحل والدوام</h2><form onSubmit={saveOperation} className="grid gap-4 md:grid-cols-3"><div className="space-y-2"><Label>حالة المحل</Label><select name="operationStatus" defaultValue={operationSettings.operationStatus || "OPEN"} className="h-11 w-full rounded-xl border bg-white px-4 text-sm"><option value="OPEN">مفتوح الآن</option><option value="CLOSED">مغلق حالياً</option><option value="VACATION">في إجازة</option><option value="PAUSED">متوقف مؤقتاً</option></select></div><Field label="ملاحظة تظهر للعملاء" name="operationNote" defaultValue={operationSettings.operationNote || ""} placeholder="مثال: نعود غداً الساعة 10 صباحاً"/><div className="space-y-2 md:col-span-3"><Label>أوقات الدوام JSON</Label><Textarea name="businessHours" defaultValue={JSON.stringify(operationSettings.businessHours || {}, null, 2)} placeholder='{"sat":{"open":"09:00","close":"22:00"}}' className="font-mono text-xs"/><p className="text-xs font-bold text-slate-500">يمكنك لاحقاً ربطها بواجهة أوقات أكثر تفصيلاً. الآن تحفظ كجدول مرن.</p></div><Button className="md:col-span-3">حفظ حالة المحل</Button></form></section>
    <section className="rounded-3xl border bg-white p-6 shadow-card"><h2 className="mb-4 text-xl font-black">وضع الربط المالي والمخزني</h2><form onSubmit={saveIntegration} className="grid gap-4 md:grid-cols-3"><div className="rounded-2xl bg-slate-50 p-4"><p className="text-xs font-bold text-slate-500">الوضع الحالي</p><p className="mt-1 font-black">{integrationSettings.integrationMode}</p></div><div className="rounded-2xl bg-slate-50 p-4"><p className="text-xs font-bold text-slate-500">مزود ERP</p><p className="mt-1 font-black">{integrationSettings.erpProvider || "غير مفعّل"}</p></div><div className="rounded-2xl bg-slate-50 p-4"><p className="text-xs font-bold text-slate-500">حالة فتح الميزة</p><p className="mt-1 font-black">{integrationSettings.erpAccess === "admin_enabled" ? "مفتوحة من الإدارة" : "مقفلة حتى اعتماد الإدارة"}</p></div><p className="rounded-2xl bg-blue-50 p-3 text-xs font-bold leading-6 text-blue-700 md:col-span-3">سياسات المصدر الحقيقي: المخزون والفاتورة والإيراد المحاسبي من ERP فقط عند فتح الإدارة للوضع المعتمد؛ تبقى التسويات وpayouts، السعر، بيانات المنتج، الحسابات البنكية وبيانات العملاء على المنصة/التاجر حسب السياسة المعتمدة. لا يستطيع التاجر فتح ERP مباشرة.</p>{integrationSettings.integrationMode === "ERP" ? null : <Button className="md:col-span-3">تثبيت وضع Standalone</Button>}</form></section>
    <section className="rounded-3xl border bg-white p-6 shadow-card"><h2 className="mb-4 text-xl font-black">إعدادات الطلبات الخاصة بالمتجر</h2><form onSubmit={saveOrders} className="grid gap-4 md:grid-cols-3"><label className="flex items-center gap-2 font-bold"><input name="autoAcceptOrders" type="checkbox" defaultChecked={orderSettings.autoAcceptOrders}/> قبول تلقائي للطلبات</label><label className="flex items-center gap-2 font-bold"><input name="allowCancellation" type="checkbox" defaultChecked={orderSettings.allowCancellation}/> السماح بالإلغاء</label><Field label="مهلة الإلغاء بالساعات" name="cancellationHours" type="number" defaultValue={orderSettings.cancellationHours}/><Field label="أقل مبلغ طلب" name="minOrderAmount" type="number" defaultValue={orderSettings.minOrderAmount}/><Field label="وقت التجهيز بالدقائق" name="preparationMinutes" type="number" defaultValue={orderSettings.preparationMinutes}/><label className="flex items-center gap-2 font-bold"><input name="enableReservationExpiry" type="checkbox" defaultChecked={Boolean(orderSettings.enableReservationExpiry)}/> تفعيل انتهاء حجز المخزون تلقائياً</label><Field label="مدة حجز المخزون بالدقائق" name="reservationExpiryMinutes" type="number" defaultValue={orderSettings.reservationExpiryMinutes || 120}/><p className="rounded-2xl bg-amber-50 p-3 text-xs font-bold leading-6 text-amber-700 md:col-span-3">هذه المدة يحددها التاجر. إذا لم يتم تفعيلها فلن يفرض النظام إلغاء تلقائي للحجز، ويبقى الإلغاء/الفك يدوياً أو عند رد ERP.</p><div className="space-y-2 md:col-span-3"><Label>سياسة الشحن</Label><Textarea name="shippingPolicy" defaultValue={orderSettings.shippingPolicy}/></div><div className="space-y-2 md:col-span-3"><Label>سياسة الإرجاع</Label><Textarea name="returnPolicy" defaultValue={orderSettings.returnPolicy}/></div><div className="space-y-2 md:col-span-3"><Label>ملاحظات الطلبات</Label><Textarea name="notes" defaultValue={orderSettings.notes}/></div><Button className="md:col-span-3">حفظ إعدادات الطلبات</Button></form></section>
  </div>;
}
function List<T extends {id:string}>({items,render}:{items:T[];render:(item:T)=>React.ReactNode}){return <div className="mt-5 space-y-3">{items.map(item=><div key={item.id} className="rounded-2xl border bg-slate-50 p-4 text-sm">{render(item)}</div>)}</div>}
function Field({label,name,type="text",required=false,placeholder,defaultValue}:{label:string;name:string;type?:string;required?:boolean;placeholder?:string;defaultValue?:string|number}){return <div className="space-y-2"><Label>{label}</Label><Input name={name} type={type} required={required} placeholder={placeholder||""} defaultValue={defaultValue}/></div>}
