"use client";

import { FormEvent, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { MediaUrlInput } from "@/components/media/media-url-input";
import { apiClient, ApiClientError } from "@/lib/client/api-client";
import { formatCurrency } from "@/lib/utils";

type Props = { terms: any[]; statements: any[]; reports: any[]; promotionAgreements: any[] };
function previousMonth() { const now=new Date(); const start=new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth()-1,1)); const end=new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),1)); return { start:start.toISOString().slice(0,16), end:end.toISOString().slice(0,16) }; }
function variant(status:string){return status==="paid"||status==="approved"||status==="active"?"success" as const:status==="overdue"||status==="rejected"||status==="suspended"?"danger" as const:"warning" as const;}
export function PlatformRevenuePanel({terms,statements,reports,promotionAgreements}:Props){
 const router=useRouter();const defaults=useMemo(previousMonth,[]);const [message,setMessage]=useState<string|null>(null);const [loading,setLoading]=useState(false);const [proofStatement,setProofStatement]=useState<any|null>(null);const [proofUrl,setProofUrl]=useState("");
 const primaryTerm=terms[0]?.terms;const primaryStoreId=primaryTerm?.storeId||statements[0]?.statement.storeId||"";
 async function submitReport(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);setLoading(true);setMessage(null);try{const data=await apiClient.post<any>("/api/merchant/platform-revenue/sales-reports",{periodStart:new Date(String(form.get("periodStart"))).toISOString(),periodEnd:new Date(String(form.get("periodEnd"))).toISOString(),salesTotal:Number(form.get("salesTotal")||0),currency:"YER",externalReference:form.get("externalReference")||null,note:form.get("note")||null},{invalidateTags:["merchant:platform-revenue"]});setMessage(data.message||"تم إرسال التقرير");event.currentTarget.reset();router.refresh();}catch(caught){setMessage(caught instanceof ApiClientError?caught.message:"تعذر إرسال التقرير");}finally{setLoading(false);}}
 async function submitProof(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!proofStatement||!proofUrl)return;setLoading(true);setMessage(null);try{const form=new FormData(event.currentTarget);const data=await apiClient.post<any>(`/api/merchant/platform-revenue/statements/${proofStatement.id}/proof`,{proofUrl,paymentReference:form.get("paymentReference")||null,note:form.get("note")||null},{invalidateTags:["merchant:platform-revenue"]});setMessage(data.message||"تم إرسال الإثبات");setProofStatement(null);setProofUrl("");router.refresh();}catch(caught){setMessage(caught instanceof ApiClientError?caught.message:"تعذر إرسال الإثبات");}finally{setLoading(false);}}
 return <div className="space-y-8">{message?<p className="rounded-2xl border bg-white p-4 text-sm font-bold text-slate-700">{message}</p>:null}<section className="grid gap-4 lg:grid-cols-2"><article className="rounded-3xl border bg-white p-6 shadow-card"><h2 className="text-xl font-black">نموذج علاقتك المالية بالمنصة</h2>{primaryTerm?<div className="mt-4 grid grid-cols-2 gap-3 text-sm"><Item label="النموذج" value={primaryTerm.model}/><Item label="الإيجار" value={formatCurrency(primaryTerm.monthlyRent,primaryTerm.currency)}/><Item label="العمولة" value={`${primaryTerm.commissionRate}%`}/><Item label="السماح" value={`${primaryTerm.graceDays} يوم`}/></div>:<p className="mt-3 text-sm text-slate-500">لم تعتمد الإدارة شروط إيراد المنصة لمتجرك بعد.</p>}<p className="mt-4 text-xs font-bold leading-6 text-slate-500">العميل يدفع للتاجر مباشرة. هذه الشروط تخص فقط إيجار المنصة والعمولة وإضافاتها.</p></article><article className="rounded-3xl border bg-white p-6 shadow-card"><h2 className="text-xl font-black">اتفاق الإعلانات والظهور</h2>{promotionAgreements[0]?.agreement?<div className="mt-4 grid grid-cols-2 gap-3 text-sm"><Item label="بنر الرئيسية" value={formatCurrency(promotionAgreements[0].agreement.homepageBannerFee,promotionAgreements[0].agreement.currency)}/><Item label="منتج مميز" value={formatCurrency(promotionAgreements[0].agreement.featuredProductFee,promotionAgreements[0].agreement.currency)}/><Item label="الحالة" value={promotionAgreements[0].agreement.status}/><Item label="الإصدار" value={`v${promotionAgreements[0].agreement.version}`}/></div>:<p className="mt-3 text-sm text-slate-500">لا يوجد اتفاق ترويج مفعل. تواصل مع الإدارة قبل طلب ظهور مميز.</p>}<p className="mt-4 text-xs font-bold leading-6 text-slate-500">رسوم الإعلان مستقلة عن عقد الإيجار، لكنها تظهر كسطر منفصل في كشف المنصة الموحد.</p></article></section>
 <section className="rounded-3xl border bg-white p-6 shadow-card"><h2 className="text-xl font-black">إرسال تقرير المبيعات الشهري</h2><p className="mt-1 text-xs leading-6 text-slate-500">اكتب إجمالي المبيعات التي استلمتها مباشرة من العملاء خلال الفترة. لن تحتسب عمولة قبل اعتماد الإدارة للتقرير.</p><form onSubmit={submitReport} className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-4"><label className="space-y-2 text-sm font-black"><span>بداية الفترة</span><Input name="periodStart" type="datetime-local" defaultValue={defaults.start}/></label><label className="space-y-2 text-sm font-black"><span>نهاية الفترة</span><Input name="periodEnd" type="datetime-local" defaultValue={defaults.end}/></label><label className="space-y-2 text-sm font-black"><span>إجمالي المبيعات (ريال)</span><Input name="salesTotal" type="number" min="0" required/></label><label className="space-y-2 text-sm font-black"><span>مرجع التقرير/ERP</span><Input name="externalReference"/></label><div className="md:col-span-2 xl:col-span-3"><Label>ملاحظة</Label><Textarea name="note" className="mt-2" placeholder="اختياري: رقم تقرير ERP أو ملاحظة توضيحية"/></div><Button disabled={loading} className="self-end">إرسال للمراجعة</Button></form></section>
 <section className="rounded-3xl border bg-white p-6 shadow-card"><h2 className="text-xl font-black">تقارير المبيعات</h2>{!reports.length?<Empty text="لا توجد تقارير مبيعات مرسلة."/>:<Table headers={["الفترة","إجمالي المبيعات","المصدر","الحالة","ملاحظة المراجعة"]}>{reports.map((row:any)=><tr key={row.report.id} className="border-t"><td className="p-3">{date(row.report.periodStart)} — {date(row.report.periodEnd)}</td><td className="p-3 font-black">{formatCurrency(row.report.salesTotal,row.report.currency)}</td><td className="p-3">{row.report.source}</td><td className="p-3"><Badge variant={variant(row.report.status)}>{row.report.status}</Badge></td><td className="p-3 text-xs text-slate-500">{row.report.reviewNote||"-"}</td></tr>)}</Table>}</section>
 <section className="rounded-3xl border bg-white p-6 shadow-card"><h2 className="text-xl font-black">كشف إيرادات المنصة الموحد</h2><p className="mt-1 text-xs leading-6 text-slate-500">يشمل الإيجار والعمولة والإعلانات والإضافات فقط. لا يشمل ولا يخصم من أموال مبيعاتك للعملاء.</p>{!statements.length?<Empty text="لا توجد كشوف صادرة بعد."/>:<Table headers={["الرقم","الفترة","الإيجار","العمولة","الإعلانات","الإجمالي","الحالة","البنود","السداد"]}>{statements.map((row:any)=><tr key={row.statement.id} className="border-t"><td className="p-3 font-black">{row.statement.statementNumber}</td><td className="p-3">{date(row.statement.periodStart)} — {date(row.statement.periodEnd)}</td><td className="p-3">{formatCurrency(row.statement.rentAmount,row.statement.currency)}</td><td className="p-3">{formatCurrency(row.statement.commissionAmount,row.statement.currency)}</td><td className="p-3">{formatCurrency(row.statement.advertisingAmount,row.statement.currency)}</td><td className="p-3 font-black text-primary">{formatCurrency(row.statement.totalAmount,row.statement.currency)}</td><td className="p-3"><Badge variant={variant(row.statement.status)}>{row.statement.status}</Badge>{row.statement.dueAt?<div className="mt-1 text-xs text-slate-500">استحقاق: {date(row.statement.dueAt)}</div>:null}</td><td className="p-3"><details><summary className="cursor-pointer text-xs font-black text-primary">تفاصيل ({row.lines?.length || 0})</summary><ul className="mt-2 space-y-1 text-xs text-slate-600">{(row.lines || []).map((line:any)=><li key={line.id}>{line.description}: {formatCurrency(line.totalAmount,row.statement.currency)}</li>)}</ul></details></td><td className="p-3">{["issued","overdue"].includes(row.statement.status)?<Button size="sm" onClick={()=>setProofStatement(row.statement)}>رفع إثبات</Button>:row.statement.status === "payment_submitted"?<span className="text-xs font-bold text-amber-700">قيد المراجعة</span>:"-"}</td></tr>)}</Table>}</section>
 {proofStatement?<section className="rounded-3xl border border-blue-200 bg-blue-50 p-6"><h2 className="text-xl font-black">إثبات سداد {proofStatement.statementNumber}</h2><p className="mt-1 text-xs text-slate-600">هذا التحويل للمنصة فقط لسداد كشفها، وليس دفعة عميل أو مبيعات متجر.</p><form onSubmit={submitProof} className="mt-4 grid gap-4 md:grid-cols-2"><MediaUrlInput label="صورة أو PDF إثبات السداد" name="proofUrl" value={proofUrl} onValueChange={setProofUrl} storeId={primaryStoreId} folder="platform-revenue-payment-proofs" accept="image/*,application/pdf"/><label className="space-y-2 text-sm font-black"><span>مرجع التحويل</span><Input name="paymentReference"/></label><div className="md:col-span-2"><Label>ملاحظة</Label><Textarea name="note" className="mt-2"/></div><div className="flex gap-2 md:col-span-2"><Button disabled={loading||!proofUrl}>إرسال الإثبات</Button><Button type="button" variant="outline" disabled={loading} onClick={()=>{setProofStatement(null);setProofUrl("");}}>إلغاء</Button></div></form></section>:null}
 </div>;
}
function Item({label,value}:{label:string;value:string|number}){return <div className="rounded-xl bg-slate-50 p-3"><span className="text-xs text-slate-500">{label}</span><b className="mt-1 block text-slate-950">{value}</b></div>}
function Empty({text}:{text:string}){return <p className="mt-4 rounded-2xl border border-dashed bg-slate-50 p-5 text-sm font-bold text-slate-500">{text}</p>}
function Table({headers,children}:{headers:string[];children:React.ReactNode}){return <div className="mt-4 overflow-x-auto"><table className="w-full min-w-[950px] text-right text-sm"><thead className="bg-slate-100"><tr>{headers.map(h=><th key={h} className="p-3">{h}</th>)}</tr></thead><tbody>{children}</tbody></table></div>}
function date(value:string|Date){return new Intl.DateTimeFormat("ar",{dateStyle:"short"}).format(new Date(value));}
