"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { Archive, CalendarClock, PauseCircle, Send, PlayCircle } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";

type Action = "submit_review" | "pause" | "resume" | "archive" | "schedule_publish" | "schedule_pause";
export function ProductLifecycleControls({ productId, status, publishAt, unpublishAt }: { productId: string; status: string; publishAt?: string | Date | null; unpublishAt?: string | Date | null }) {
  const router = useRouter(); const [loading, setLoading] = useState<Action | null>(null); const [message, setMessage] = useState<string | null>(null);
  async function execute(action: Action) { let schedule: Record<string, string | null> = {}; if (action === "schedule_publish" || action === "schedule_pause") { const raw = window.prompt(action === "schedule_publish" ? "وقت النشر (ISO مثل 2026-07-15T09:00:00.000Z):" : "وقت الإيقاف (ISO):"); if (!raw) return; schedule = action === "schedule_publish" ? { publishAt: new Date(raw).toISOString() } : { unpublishAt: new Date(raw).toISOString() }; } const reason = ["submit_review", "pause", "archive"].includes(action) ? (window.prompt("سبب/ملاحظة اختيارية:") || null) : null; setLoading(action); const response = await fetch(`/api/merchant/products/${productId}/lifecycle`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action, reason, ...schedule }) }); const json = await response.json().catch(() => ({})); setLoading(null); setMessage(response.ok ? "✓ تم تحديث دورة حياة المنتج" : json.message || "تعذر تحديث الحالة"); if (response.ok) router.refresh(); }
  return <section className="rounded-3xl border bg-white p-5 shadow-card"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-black">دورة حياة المنتج</h2><p className="mt-1 text-sm text-slate-500">مسودة → مراجعة → نشط، مع إيقاف وأرشفة وجدولة نشر/إيقاف.</p></div><Badge variant={status === "active" ? "success" : status === "paused" || status === "archived" ? "warning" : "outline"}>{status}</Badge></div><div className="mt-4 flex flex-wrap gap-2">{["draft", "paused", "inactive"].includes(status) ? <Button size="sm" disabled={Boolean(loading)} onClick={() => void execute("submit_review")}><Send className="h-4 w-4"/> إرسال للمراجعة</Button> : null}{status === "active" ? <Button size="sm" variant="outline" disabled={Boolean(loading)} onClick={() => void execute("pause")}><PauseCircle className="h-4 w-4"/> إيقاف مؤقت</Button> : null}{["paused", "inactive"].includes(status) ? <Button size="sm" disabled={Boolean(loading)} onClick={() => void execute("resume")}><PlayCircle className="h-4 w-4"/> استئناف</Button> : null}<Button size="sm" variant="outline" disabled={Boolean(loading)} onClick={() => void execute("schedule_publish")}><CalendarClock className="h-4 w-4"/> جدولة نشر</Button><Button size="sm" variant="outline" disabled={Boolean(loading)} onClick={() => void execute("schedule_pause")}><CalendarClock className="h-4 w-4"/> جدولة إيقاف</Button><Button size="sm" variant="destructive" disabled={Boolean(loading) || status === "archived"} onClick={() => void execute("archive")}><Archive className="h-4 w-4"/> أرشفة</Button></div>{publishAt ? <p className="mt-3 text-xs font-bold text-blue-700">نشر مجدول: {new Intl.DateTimeFormat("ar", { dateStyle: "short", timeStyle: "short" }).format(new Date(publishAt))}</p> : null}{unpublishAt ? <p className="mt-1 text-xs font-bold text-amber-700">إيقاف مجدول: {new Intl.DateTimeFormat("ar", { dateStyle: "short", timeStyle: "short" }).format(new Date(unpublishAt))}</p> : null}{message ? <p className="mt-3 text-sm font-bold text-slate-600">{message}</p> : null}</section>;
}
