"use client";

import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { ClipboardCheck } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";

type Count = { id: string; title: string; status: string; createdAt: string; appliedAt: string | null };
type Line = { line: { id: string; expectedQuantity: number; countedQuantity: number | null; note: string | null }; sku: string; title: string | null };

export function StockCountPanel() {
  const router = useRouter(); const [counts, setCounts] = useState<Count[]>([]); const [active, setActive] = useState<{ id: string; lines: Line[]; status: string } | null>(null); const [message, setMessage] = useState<string | null>(null); const [loading, setLoading] = useState(false);
  async function load() { const response = await fetch("/api/merchant/inventory/stock-counts", { cache: "no-store" }); const json = await response.json().catch(() => ({})); if (response.ok) setCounts(json.data?.counts || []); }
  useEffect(() => { void load(); }, []);
  async function create() { const title = window.prompt("اسم جلسة الجرد:", "جرد دوري") || ""; if (!title) return; setLoading(true); const response = await fetch("/api/merchant/inventory/stock-counts", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ title }) }); const json = await response.json().catch(() => ({})); setLoading(false); setMessage(response.ok ? `✓ ${json.data?.message || "تم فتح الجرد"}` : json.message || "تعذر فتح الجرد"); if (response.ok) { await load(); router.refresh(); } }
  async function open(id: string) { setLoading(true); const response = await fetch(`/api/merchant/inventory/stock-counts/${id}`, { cache: "no-store" }); const json = await response.json().catch(() => ({})); setLoading(false); if (!response.ok) return setMessage(json.message || "تعذر تحميل الجرد"); setActive({ id, lines: json.data.lines || [], status: json.data.count.status }); }
  function updateLine(id: string, countedQuantity: number) { setActive((current) => current ? { ...current, lines: current.lines.map((row) => row.line.id === id ? { ...row, line: { ...row.line, countedQuantity } } : row) } : current); }
  async function save(apply = false) { if (!active) return; setLoading(true); const response = await fetch(`/api/merchant/inventory/stock-counts/${active.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: apply ? "apply" : "set_lines", lines: active.lines.map((row) => ({ id: row.line.id, countedQuantity: row.line.countedQuantity ?? 0, note: row.line.note })) }) }); const json = await response.json().catch(() => ({})); setLoading(false); setMessage(response.ok ? `✓ ${json.data?.message || "تم الحفظ"}` : json.message || "تعذر حفظ الجرد"); if (response.ok) { await load(); if (apply) setActive(null); router.refresh(); } }
  return <section className="mt-8 rounded-3xl border bg-white p-6 shadow-card"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="flex items-center gap-2 text-xl font-black"><ClipboardCheck className="h-5 w-5 text-primary"/> الجرد الدوري Stock Count</h2><p className="mt-1 text-sm text-slate-500">خذ لقطة للمخزون، أدخل الكمية الفعلية، ثم طبّق فروقات الجرد كسجل ضبط موثق.</p></div><Button disabled={loading} onClick={create}>فتح جرد جديد</Button></div>{message ? <p className="mt-4 rounded-2xl border bg-slate-50 p-3 text-sm font-bold text-slate-700">{message}</p> : null}<div className="mt-5 flex flex-wrap gap-2">{counts.map((count) => <Button key={count.id} size="sm" variant={active?.id === count.id ? "default" : "outline"} onClick={() => void open(count.id)}>{count.title} <Badge variant={count.status === "applied" ? "success" : "warning"}>{count.status}</Badge></Button>)}</div>{active ? <div className="mt-5 overflow-x-auto rounded-2xl border"><table className="w-full min-w-[720px] text-right text-sm"><thead className="bg-slate-100"><tr><th className="p-3">المتغير</th><th className="p-3">المتوقع</th><th className="p-3">المعدود</th></tr></thead><tbody>{active.lines.map((row) => <tr key={row.line.id} className="border-t"><td className="p-3"><b>{row.title || "افتراضي"}</b><div className="text-xs text-slate-400">{row.sku}</div></td><td className="p-3">{row.line.expectedQuantity}</td><td className="p-3"><Input type="number" min={0} disabled={active.status === "applied"} value={row.line.countedQuantity ?? ""} onChange={(event) => updateLine(row.line.id, Number(event.target.value || 0))}/></td></tr>)}</tbody></table></div> : null}{active && active.status !== "applied" ? <div className="mt-4 flex gap-2"><Button disabled={loading} variant="outline" onClick={() => void save(false)}>حفظ الكميات</Button><Button disabled={loading} onClick={() => { if (window.confirm("سيتم ضبط المخزون فعليًا حسب الكميات المعدودة. هل تريد المتابعة؟")) void save(true); }}>تطبيق الجرد</Button></div> : null}</section>;
}
