"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { CheckCircle2, Circle } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { apiClient, ApiClientError } from "@/lib/client/api-client";
type Check={key:string;label:string;ok:boolean;detail:string;critical:boolean};
export function StoreLaunchReadinessPanel({initial}:{initial:{readiness:any;checks:Check[];ready:boolean}}){const router=useRouter();const [note,setNote]=useState("");const [loading,setLoading]=useState(false);const [message,setMessage]=useState<string|null>(null);async function submit(){setLoading(true);setMessage(null);try{const data=await apiClient.post<any>("/api/merchant/store-launch-readiness",{note},{invalidateTags:["merchant:launch"]});setMessage(data.message||"تم الإرسال");router.refresh()}catch(caught){setMessage(caught instanceof ApiClientError?caught.message:"تعذر الإرسال")}finally{setLoading(false)}}return <section className="space-y-6"><div className="rounded-3xl border bg-white p-6 shadow-card"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-2xl font-black text-slate-950">جاهزية إطلاق المتجر للعموم</h2><p className="mt-2 text-sm leading-7 text-slate-500">حسابك معتمد، لكن لا يظهر المتجر للعملاء حتى تعتمد الإدارة checklist الإطلاق.</p></div><Badge variant={initial.readiness?.status==="approved"?"success":initial.readiness?.status==="submitted"?"warning":"outline"}>{initial.readiness?.status||"setup_pending"}</Badge></div><div className="mt-5 grid gap-3 md:grid-cols-2">{initial.checks.map((check)=><article key={check.key} className={`rounded-2xl border p-4 ${check.ok?"border-emerald-100 bg-emerald-50":"bg-slate-50"}`}><div className="flex items-start gap-3">{check.ok?<CheckCircle2 className="h-5 w-5 text-emerald-600"/>:<Circle className="h-5 w-5 text-slate-400"/>}<div><h3 className="font-black text-slate-950">{check.label}{check.critical?<span className="mr-1 text-red-600">*</span>:null}</h3><p className="mt-1 text-xs leading-6 text-slate-600">{check.detail}</p></div></div></article>)}</div></div>{initial.ready&&initial.readiness?.status!=="approved"?<div className="rounded-3xl border bg-blue-50 p-6"><h3 className="font-black text-blue-950">المتجر مستوفٍ للحد الأدنى</h3><Textarea value={note} onChange={(event)=>setNote(event.target.value)} className="mt-3 bg-white" placeholder="ملاحظة اختيارية للإدارة"/><Button className="mt-3" disabled={loading} onClick={()=>void submit()}>{loading?"جارٍ الإرسال...":"إرسال للمراجعة والنشر"}</Button>{message?<p className="mt-3 text-sm font-bold text-slate-700">{message}</p>:null}</div>:<p className="rounded-2xl border border-dashed bg-white p-5 text-sm font-bold text-slate-500">أكمل البنود الإلزامية المعلّمة بنجمة قبل إرسال المتجر للمراجعة.</p>}</section>}
