export const dynamic="force-dynamic";
import { eq } from "drizzle-orm";
import { z } from "zod";
import { fail, handleApiError, ok } from "@/lib/api";
import { db, notifications, stores, users } from "@/lib/db";
import { checkIpRateLimit } from "@/lib/rate-limit";
import { issuePasswordResetInvite } from "@/lib/auth/password-recovery";
import { sendOptionalActivationMessages } from "@/lib/outbound";
import { writeAuditLog } from "@/lib/audit";
const schema=z.object({identifier:z.string().trim().min(2).max(255)});
export async function POST(request:Request){try{const rate=await checkIpRateLimit("auth:recover-store-credentials",5,15*60*1000);if(!rate.allowed)return fail("محاولات كثيرة، حاول لاحقاً",429);const payload=schema.parse(await request.json());const normalized=payload.identifier.toLowerCase();let [user]=await db.select().from(users).where(eq(users.email,normalized)).limit(1);if(!user){const [store]=await db.select({merchantId:stores.merchantId}).from(stores).where(eq(stores.storeNumber,payload.identifier.toUpperCase())).limit(1);if(store)[user]=await db.select().from(users).where(eq(users.id,store.merchantId)).limit(1)}if(!user||user.status!=="active"){await writeAuditLog({action:"create",entityType:"store_credential_recovery",entityId:payload.identifier,afterData:{delivered:false}});return ok({message:"إذا كانت البيانات صحيحة فسيتم إرسال بيانات الاستعادة إلى جهة التواصل المعتمدة."});}const ownedStores=await db.select({storeNumber:stores.storeNumber,name:stores.name,status:stores.status}).from(stores).where(eq(stores.merchantId,user.id));const invite=await issuePasswordResetInvite({user,identifier:payload.identifier,requestUrl:request.url,purpose:"credentials_recovery",expiresMinutes:30});const storeList=ownedStores.map(store=>`${store.name} (${store.storeNumber})`).join("، ")||"لا توجد متاجر مرتبطة";await db.insert(notifications).values({userId:user.id,title:"استعادة بيانات المتجر",body:`بيانات متاجرك: ${storeList}. تم إرسال رابط آمن لإعادة تعيين كلمة المرور.`,type:"store_credentials_recovery",data:{storeNumbers:ownedStores.map(store=>store.storeNumber),resetUrl:invite.resetUrl,expiresAt:invite.expiresAt.toISOString()}});await sendOptionalActivationMessages({email:user.email,phone:user.phone,subject:"استعادة بيانات المتجر",message:`بيانات متاجرك: ${storeList}. استخدم رابط إعادة التعيين الآمن المرسل لك لتعيين كلمة مرور جديدة.`});await writeAuditLog({actorId:user.id,action:"create",entityType:"store_credential_recovery",entityId:user.id,afterData:{delivered:true,stores:ownedStores.map(store=>store.storeNumber)}});return ok({message:"إذا كانت البيانات صحيحة فسيتم إرسال بيانات الاستعادة إلى جهة التواصل المعتمدة."});}catch(error){return handleApiError(error,"تعذر معالجة طلب استعادة بيانات المتجر");}}
