"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { FileCheck2, FileUp } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { MediaUrlInput } from "@/components/media/media-url-input";
import { apiClient, ApiClientError } from "@/lib/client/api-client";

type Row = { requirement: { id: string; documentType: string; title: string; isRequired: boolean; status: string; note?: string | null }; document: { id: string; fileUrl: string; downloadUrl?: string; fileName?: string | null; status: string } | null };
const labels: Record<string,string> = { requested:"مطلوبة",uploaded:"مرفوعة بانتظار المراجعة",approved:"معتمدة",rejected:"مرفوضة",waived:"معفاة" };
function tone(status:string){return status === "approved"||status === "waived"?"success" as const:status === "rejected"?"danger" as const:"warning" as const;}

export function MerchantApplicationDocumentsPanel({ applicationId, rows, enabled }: { applicationId: string; rows: Row[]; enabled: boolean }) {
  const router=useRouter(); const [urls,setUrls]=useState<Record<string,string>>({}); const [loading,setLoading]=useState<string|null>(null); const [message,setMessage]=useState<string|null>(null);
  async function submit(row:Row){const url=urls[row.requirement.id];if(!url)return;setLoading(row.requirement.id);setMessage(null);try{const data=await apiClient.post<any>(`/api/merchant-applications/${applicationId}/documents`,{documentType:row.requirement.documentType,fileUrl:url,title:row.requirement.title},{invalidateTags:[`application:${applicationId}`]});setMessage(data.message||"تم رفع الوثيقة");setUrls((current)=>({...current,[row.requirement.id]:""}));router.refresh()}catch(caught){setMessage(caught instanceof ApiClientError?caught.message:"تعذر رفع الوثيقة")}finally{setLoading(null)}}
  return <section className="rounded-[2rem] border bg-white p-6 shadow-card"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="text-xl font-black text-slate-950">الوثائق الثبوتية</h2><p className="mt-1 text-xs leading-6 text-slate-500">ترفع الوثائق القانونية بصيغة PDF فقط وتحفظ في أرشيف الطلب. الرفع لا يعني الاعتماد؛ تراجعها الإدارة بصورة مستقلة.</p></div><FileCheck2 className="h-6 w-6 text-blue-600"/></div>{message?<p className="mt-4 rounded-xl bg-slate-50 p-3 text-sm font-bold text-slate-700">{message}</p>:null}<div className="mt-5 space-y-4">{rows.map((row)=><article key={row.requirement.id} className="rounded-2xl border bg-slate-50 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-black text-slate-950">{row.requirement.title}{row.requirement.isRequired?<span className="mr-1 text-red-600">*</span>:null}</h3><p className="mt-1 text-xs text-slate-500">{row.requirement.documentType}</p></div><Badge variant={tone(row.requirement.status)}>{labels[row.requirement.status]||row.requirement.status}</Badge></div>{row.requirement.note?<p className="mt-3 rounded-xl bg-amber-50 p-3 text-sm font-bold text-amber-800">ملاحظة الإدارة: {row.requirement.note}</p>:null}{row.document?<a className="mt-3 flex items-center gap-2 text-sm font-black text-primary underline" href={row.document.downloadUrl || row.document.fileUrl} target="_blank"><FileUp className="h-4 w-4"/> فتح PDF المرفوع: {row.document.fileName||"الوثيقة"}</a>:null}{enabled&&["requested","rejected"].includes(row.requirement.status)?<div className="mt-4"><MediaUrlInput label={row.requirement.status==="rejected"?"ارفع نسخة PDF مصححة":"ارفع وثيقة PDF"} name={`document-${row.requirement.id}`} value={urls[row.requirement.id]||""} onValueChange={(value)=>setUrls((current)=>({...current,[row.requirement.id]:value}))} folder={`merchant-application-documents/${applicationId}`} accept="application/pdf"/><Button className="mt-3" size="sm" disabled={loading===row.requirement.id||!urls[row.requirement.id]} onClick={()=>void submit(row)}>{loading===row.requirement.id?"جارٍ الحفظ...":"إرسال للمراجعة"}</Button></div>:null}</article>)}</div></section>
}
