export const dynamic="force-dynamic";
import { z } from "zod";
import { handleApiError, ok } from "@/lib/api";
import { requireAuth } from "@/lib/auth";
import { assertAdminOperation } from "@/lib/rbac";
import { activateSignedIdentityAddendum, createIdentityChangeAddendum, getAdminIdentityChangeRequests } from "@/lib/contracts/addendums";
import { db, notifications, storeIdentityChangeRequests } from "@/lib/db";
import { eq } from "drizzle-orm";
import { writeAuditLog } from "@/lib/audit";
const schema=z.object({requestId:z.string().uuid(),action:z.enum(["create_addendum","reject","activate_addendum"]),note:z.string().trim().min(3).max(2000).optional()});
export async function GET(){try{const session=await requireAuth();await assertAdminOperation(session,"stores.identity_changes.review");return ok({requests:await getAdminIdentityChangeRequests()});}catch(error){return handleApiError(error,"تعذر تحميل طلبات هوية المتاجر");}}
export async function PATCH(request:Request){try{const session=await requireAuth();const payload=schema.parse(await request.json());await assertAdminOperation(session,payload.action==="activate_addendum"?"contracts.addendum.manage":"stores.identity_changes.review");if(payload.action==="create_addendum"){const result=await createIdentityChangeAddendum({requestId:payload.requestId,actorId:session.userId,note:payload.note});await writeAuditLog({actorId:session.userId,action:"create",entityType:"merchant_contract_addendum",entityId:result.addendum.id,beforeData:result.request,afterData:{addendum:result.addendum,request:result.request,accessTokenReturnedOnce:true}});return ok({...result,warning:"رابط/رمز الملحق يرسل للتاجر عبر إشعار. لا تحفظ access token في المصدر أو ملاحظات الدعم.",message:"تم إنشاء ملحق العقد وإرساله للتاجر للتوقيع"});}const [before]=await db.select().from(storeIdentityChangeRequests).where(eq(storeIdentityChangeRequests.id,payload.requestId)).limit(1);if(!before)throw new Error("طلب تعديل الهوية غير موجود");if(payload.action==="reject"){const [updated]=await db.update(storeIdentityChangeRequests).set({status:"rejected",reviewedBy:session.userId,reviewedAt:new Date(),adminNote:payload.note||null,updatedAt:new Date()}).where(eq(storeIdentityChangeRequests.id,before.id)).returning();await db.insert(notifications).values({userId:updated.merchantId,storeId:updated.storeId,title:"تم رفض طلب تعديل بيانات المتجر",body:payload.note||"تم رفض الطلب.",type:"store_identity_change_rejected",data:{requestId:updated.id}});await writeAuditLog({actorId:session.userId,action:"reject",entityType:"store_identity_change_request",entityId:updated.id,beforeData:before,afterData:updated});return ok({request:updated,message:"تم رفض طلب تعديل هوية المتجر"});}if(!before.addendumId)throw new Error("لا يوجد ملحق عقد مرتبط بالطلب");const result=await activateSignedIdentityAddendum({addendumId:before.addendumId,actorId:session.userId,note:payload.note});await db.insert(notifications).values({userId:result.request.merchantId,storeId:result.request.storeId,title:"تم اعتماد تعديل بيانات المتجر",body:"تم اعتماد الملحق وتطبيق التعديل على بيانات المتجر.",type:"store_identity_change_approved",data:{requestId:result.request.id,addendumId:result.addendum.id}});await writeAuditLog({actorId:session.userId,action:"approve",entityType:"store_identity_change_request",entityId:result.request.id,beforeData:before,afterData:result});return ok({...result,message:"تم اعتماد الملحق وتطبيق تعديل بيانات المتجر"});}catch(error){return handleApiError(error,"تعذر مراجعة طلب تعديل هوية المتجر");}}
