import Link from "next/link";
import { eq } from "drizzle-orm";
import { FileSignature } from "lucide-react";
import { SiteHeader } from "@/components/layout/site-header";
import { Button } from "@/components/ui/button";
import { ContractAddendumSignatureForm } from "@/components/contracts/contract-addendum-signature-form";
import { db, merchantContractAddendums, users } from "@/lib/db";
import { getCurrentSession, hasRole } from "@/lib/auth";
import { safeCompareHash } from "@/lib/security";
export default async function ContractAddendumPage({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<{token?:string}>}){const {id}=await params;const {token}=await searchParams;const session=await getCurrentSession();const [row]=await db.select({addendum:merchantContractAddendums,merchantName:users.fullName}).from(merchantContractAddendums).innerJoin(users,eq(merchantContractAddendums.merchantId,users.id)).where(eq(merchantContractAddendums.id,id)).limit(1);if(!row)return <main className="min-h-screen"><SiteHeader/><section className="container py-10">الملحق غير موجود</section></main>;const access=Boolean((session&&hasRole(session,"super_admin"))||(session?.userId===row.addendum.merchantId)||safeCompareHash(token,row.addendum.accessTokenHash));if(!access)return <main className="min-h-screen"><SiteHeader/><section className="container py-10">لا تملك صلاحية الوصول إلى الملحق</section></main>;const returnHref=(row.addendum.changes as any)?.kind==="branch_financial_terms"?"/merchant/branches":"/merchant/identity-change-requests";return <main className="min-h-screen bg-slate-50"><SiteHeader/><section className="container space-y-6 py-8"><div className="rounded-3xl border bg-white p-6 shadow-card"><FileSignature className="h-8 w-8 text-blue-600"/><h1 className="mt-3 text-3xl font-black">{row.addendum.title}</h1><p className="mt-2 text-sm text-slate-500">رقم الملحق: {row.addendum.amendmentNumber} · الإصدار: {row.addendum.version}</p></div><div className="grid gap-6 xl:grid-cols-[1fr_390px]"><pre className="max-h-[720px] overflow-auto whitespace-pre-wrap rounded-3xl border bg-white p-6 text-sm leading-8 shadow-card">{row.addendum.bodySnapshot}</pre>{row.addendum.status==="pending_signature"?<ContractAddendumSignatureForm addendumId={row.addendum.id} version={row.addendum.version} applicantName={row.merchantName||""} token={token}/>:<div className="rounded-3xl border bg-white p-6 shadow-card"><p className="font-black">حالة الملحق: {row.addendum.status}</p>{row.addendum.signatureUrl?<img className="mt-4 rounded-xl border" src={row.addendum.signatureUrl} alt="التوقيع"/>:null}<Button asChild className="mt-4"><Link href={returnHref}>العودة</Link></Button></div>}</div></section></main>}
