"use client";

import { useEffect, useState } from "react";
import { Copy, KeyRound, ShieldCheck, ShieldAlert } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

type Assurance = { mfaEnabled: boolean; lastVerifiedAt: string | null; activeSessions: number; canEnrollMfa: boolean; enforced: boolean; message: string };
type Setup = { secret: string; otpauthUrl: string; backupCodes: string[]; recoveryCodes: string[] };

export function AdminAccessAssurancePanel() {
  const [state, setState] = useState<Assurance | null>(null); const [setup, setSetup] = useState<Setup | null>(null); const [code, setCode] = useState(""); const [loading, setLoading] = useState<string | null>(null); const [message, setMessage] = useState<string | null>(null);
  async function refresh() { const response = await fetch("/api/admin/security/access-assurance", { cache: "no-store" }); const json = await response.json().catch(() => ({})); if (response.ok) setState(json.data); }
  useEffect(() => { void refresh(); }, []);
  async function enroll() { setLoading("setup"); setMessage(null); try { const response = await fetch("/api/auth/mfa/setup", { method: "POST" }); const json = await response.json(); if (!response.ok) throw new Error(json.message || "تعذر إعداد MFA"); setSetup(json.data); setMessage("احفظ أكواد الاسترداد في مكان آمن ثم أدخل الرمز من تطبيق المصادقة."); } catch (error) { setMessage(error instanceof Error ? error.message : "تعذر إعداد MFA"); } finally { setLoading(null); } }
  async function verify() { if (!code.trim()) return; setLoading("verify"); setMessage(null); try { const response = await fetch("/api/auth/mfa/verify", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ token: code, mode: "setup" }) }); const json = await response.json(); if (!response.ok) throw new Error(json.message || "الرمز غير صحيح"); setSetup(null); setCode(""); setMessage("تم تفعيل MFA. لا يوجد تغيير على صلاحياتك أو مسارات عملك."); await refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "تعذر التحقق"); } finally { setLoading(null); } }
  async function copy(value: string) { try { await navigator.clipboard.writeText(value); setMessage("تم النسخ."); } catch { setMessage("تعذر النسخ؛ انسخ القيمة يدوياً."); } }
  if (!state) return <section className="rounded-3xl border bg-white p-5 text-sm font-bold text-slate-500">جارٍ فحص وضع وصول الأدمن...</section>;
  return <section className={`rounded-3xl border p-5 shadow-card ${state.mfaEnabled ? "border-emerald-200 bg-emerald-50/60" : "border-amber-200 bg-amber-50/60"}`}><div className="flex flex-wrap items-start justify-between gap-4"><div className="flex gap-3"><span className={`grid h-11 w-11 place-items-center rounded-2xl ${state.mfaEnabled ? "bg-emerald-600 text-white" : "bg-amber-500 text-white"}`}>{state.mfaEnabled ? <ShieldCheck className="h-5 w-5"/> : <ShieldAlert className="h-5 w-5"/>}</span><div><h2 className="font-black text-slate-950">ضمان وصول الأدمن</h2><p className="mt-1 max-w-2xl text-sm leading-6 text-slate-600">{state.message}</p></div></div><div className="flex gap-2"><Badge variant={state.mfaEnabled ? "success" : "warning"}>{state.mfaEnabled ? "MFA مفعلة" : "MFA اختيارية وغير مفعلة"}</Badge><Badge variant="outline">جلسات نشطة: {state.activeSessions}</Badge></div></div>{!state.mfaEnabled && state.canEnrollMfa ? <div className="mt-4"><Button type="button" onClick={enroll} disabled={loading === "setup"}>{loading === "setup" ? "يجهز..." : <><KeyRound className="h-4 w-4"/> تفعيل MFA اختيارياً</>}</Button></div> : null}{setup ? <div className="mt-4 space-y-3 rounded-2xl border bg-white p-4"><p className="text-sm font-black">أدخل المفتاح في Google أو Microsoft Authenticator ثم تحقق بالرمز. الاحتفاظ بالأكواد مسؤوليتك.</p><div className="flex gap-2"><Input value={setup.secret} readOnly/><Button type="button" size="icon" variant="outline" onClick={() => copy(setup.secret)}><Copy className="h-4 w-4"/></Button></div><a className="block break-all text-xs font-bold text-blue-700 underline" href={setup.otpauthUrl}>فتح رابط المصادقة</a><div className="rounded-xl bg-slate-50 p-3 text-xs font-mono leading-6">{[...setup.backupCodes, ...setup.recoveryCodes].join("  ")}</div><div className="flex gap-2"><Input value={code} inputMode="numeric" onChange={(event) => setCode(event.target.value)} placeholder="رمز MFA"/><Button type="button" onClick={verify} disabled={loading === "verify"}>{loading === "verify" ? "يتحقق..." : "تأكيد"}</Button></div></div> : null}{message ? <p className="mt-3 text-sm font-bold text-slate-700">{message}</p> : null}</section>;
}
