"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

export function BranchReviewActions({ branchId, addendumId, addendumStatus, defaultRent = "0", defaultCommission = "0", defaultCurrency = "YER", defaultModel = "monthly_rent", defaultDueDays = "7", defaultGraceDays = "7" }: { branchId: string; addendumId?: string | null; addendumStatus?: string | null; defaultRent?: string; defaultCommission?: string; defaultCurrency?: string; defaultModel?: string; defaultDueDays?: string; defaultGraceDays?: string }) {
  const router = useRouter();
  const [rentAmount, setRentAmount] = useState(defaultRent); const [commissionRate, setCommissionRate] = useState(defaultCommission); const [rentCurrency, setRentCurrency] = useState(defaultCurrency); const [revenueModel, setRevenueModel] = useState(defaultModel); const [dueDays, setDueDays] = useState(defaultDueDays); const [graceDays, setGraceDays] = useState(defaultGraceDays); const [adminNote, setAdminNote] = useState(""); const [loading, setLoading] = useState(false);
  async function request(body: Record<string, unknown>) { setLoading(true); const response = await fetch("/api/admin/branches", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); setLoading(false); if (response.ok) router.refresh(); else alert((await response.json()).message || "تعذر تنفيذ العملية"); }
  return <div className="space-y-3"><div className="grid gap-2 md:grid-cols-3"><select value={revenueModel} onChange={(e) => setRevenueModel(e.target.value)} className="h-11 rounded-xl border bg-white px-3 text-sm"><option value="monthly_rent">إيجار شهري</option><option value="sales_commission">عمولة مبيعات</option><option value="hybrid">إيجار + عمولة</option></select><Input value={rentAmount} onChange={(e) => setRentAmount(e.target.value)} type="number" placeholder="الإيجار الشهري"/><Input value={commissionRate} onChange={(e) => setCommissionRate(e.target.value)} type="number" placeholder="نسبة العمولة %"/></div><div className="grid grid-cols-3 gap-2"><select value={rentCurrency} onChange={(e) => setRentCurrency(e.target.value)} className="h-11 rounded-xl border bg-white px-3 text-sm"><option value="YER">YER</option><option value="SAR">SAR</option><option value="USD">USD</option></select><Input value={dueDays} onChange={(e) => setDueDays(e.target.value)} type="number" placeholder="مهلة السداد"/><Input value={graceDays} onChange={(e) => setGraceDays(e.target.value)} type="number" placeholder="فترة السماح"/></div><Input value={adminNote} onChange={(e) => setAdminNote(e.target.value)} placeholder="ملاحظة الإدارة"/>{!addendumId ? <div className="flex gap-2"><Button size="sm" disabled={loading} onClick={() => request({ action: "review", branchId, status: "approved", revenueModel, rentAmount: Number(rentAmount || 0), commissionRate: Number(commissionRate || 0), rentCurrency, dueDays: Number(dueDays || 7), graceDays: Number(graceDays || 7), adminNote })}>إنشاء ملحق مالي للتوقيع</Button><Button size="sm" variant="destructive" disabled={loading} onClick={() => request({ action: "review", branchId, status: "rejected", adminNote })}>رفض</Button></div> : addendumStatus === "signed" ? <Button size="sm" disabled={loading} onClick={() => request({ action: "activate_addendum", addendumId, adminNote })}>اعتماد الملحق وتفعيل دورة الفرع</Button> : <p className="rounded-xl bg-amber-50 p-3 text-xs font-bold leading-6 text-amber-800">حالة الملحق: {addendumStatus}. لن تتفعل الدورة المالية حتى يوقّع التاجر ويصبح PDF الموقع جاهزاً.</p>}</div>;
}
