"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { ActionConfirmationDialog } from "@/components/ui/action-confirmation-dialog";
import { apiClient, ApiClientError } from "@/lib/client/api-client";

type Conflict = { id: string; entityType: string; platformEntityId: string | null; externalEntityId: string | null; conflictType: string; status: string; platformSnapshot: Record<string, unknown>; externalSnapshot: Record<string, unknown>; createdAt: string | Date };

export function ErpConflictCasePanel({ initial }: { initial: Conflict[] }) {
  const router = useRouter(); const [target, setTarget] = useState<{ conflict: Conflict; action: "resolve_platform" | "resolve_external" | "ignore" } | null>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null);
  async function resolve(reason: string) { if (!target) return; setLoading(true); setError(null); try { await apiClient.patch("/api/admin/integrations/conflicts", { id: target.conflict.id, action: target.action, note: reason }, { invalidateTags: ["erp:conflicts"] }); setTarget(null); router.refresh(); } catch (caught) { setError(caught instanceof ApiClientError ? caught.message : "تعذر معالجة التعارض"); } finally { setLoading(false); } }
  return <div className="space-y-4">{initial.map((conflict) => <article key={conflict.id} className="rounded-3xl border bg-white p-5 shadow-card"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex gap-2"><Badge variant="danger">{conflict.conflictType}</Badge><Badge variant="outline">{conflict.entityType}</Badge><Badge variant={conflict.status === "open" ? "warning" : "outline"}>{conflict.status}</Badge></div><p className="mt-3 text-sm font-bold">Platform: {conflict.platformEntityId || "—"} · External: {conflict.externalEntityId || "—"}</p><p className="mt-1 text-xs text-slate-500">{new Date(conflict.createdAt).toLocaleString("ar")}</p></div><div className="flex flex-wrap gap-2"><Button size="sm" variant="outline" onClick={() => setTarget({ conflict, action: "resolve_platform" })}>اعتماد المنصة</Button><Button size="sm" variant="outline" onClick={() => setTarget({ conflict, action: "resolve_external" })}>اعتماد ERP</Button><Button size="sm" variant="destructive" onClick={() => setTarget({ conflict, action: "ignore" })}>تجاهل موثق</Button></div></div><details className="mt-4 rounded-xl bg-slate-50 p-3"><summary className="cursor-pointer text-sm font-black">لقطات البيانات</summary><pre className="mt-3 max-h-64 overflow-auto text-left text-xs direction-ltr">{JSON.stringify({ platform: conflict.platformSnapshot, external: conflict.externalSnapshot }, null, 2)}</pre></details></article>)}{!initial.length ? <div className="rounded-3xl border bg-emerald-50 p-8 text-center font-black text-emerald-700">لا توجد حالات تعارض مفتوحة.</div> : null}<ActionConfirmationDialog open={Boolean(target)} title="حل تعارض ERP" description={`سيتم تسجيل قرار ${target?.action === "resolve_platform" ? "اعتماد بيانات المنصة" : target?.action === "resolve_external" ? "اعتماد بيانات ERP" : "تجاهل التعارض"} في سجل التدقيق.`} actionLabel="تأكيد القرار" destructive={target?.action === "ignore"} reasonRequired auditContext={`erp_conflict:${target?.conflict.id || ""}:${target?.action || ""}`} loading={loading} error={error} onClose={() => { if (!loading) { setTarget(null); setError(null); } }} onConfirm={({ reason }) => resolve(reason)} /></div>;
}
