"use client";

import { FormEvent, useState } from "react";
import { CalendarClock, CheckCircle2, CircleDollarSign, Loader2, XCircle } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";

const placements = [["homepage_featured_stores", "المتاجر المميزة"], ["homepage_trending_stores", "المتاجر الرائجة"], ["homepage_latest_stores", "أحدث المتاجر"], ["homepage_featured_products", "المنتجات المميزة"], ["homepage_trending_products", "المنتجات الرائجة"], ["homepage_latest_products", "أحدث المنتجات"], ["homepage_promoted_offers", "العروض المميزة"], ["homepage_today_offers", "عروض اليوم"], ["homepage_weekend_offers", "عروض نهاية الأسبوع"], ["homepage_seasonal_offers", "عروض موسمية"], ["homepage_hero", "البنر الرئيسي"], ["homepage_promo", "بنر Promo"], ["homepage_featured_wings", "الأجنحة والأقسام"], ["homepage_marketplace_ads", "إعلانات المول"]] as const;
const days = [[0, "الأحد"], [1, "الاثنين"], [2, "الثلاثاء"], [3, "الأربعاء"], [4, "الخميس"], [5, "الجمعة"], [6, "السبت"]] as const;
type Schedule = { mode?: string; startTime?: string | null; endTime?: string | null; weekDays?: number[] };
type Request = { id: string; status: string; placementId: string; approvedPlacementId: string | null; targetType: string; targetId: string | null; commercialModel: string; requestedStartsAt: string | null; requestedEndsAt: string | null; visibilitySchedule: Schedule; approvedStartsAt: string | null; approvedEndsAt: string | null; approvedVisibilitySchedule: Schedule; creative: Record<string, unknown>; quotedAmount: string | null; currency: string; adminNote: string | null; campaignId: string | null; financialCheckpointStatus: string; financialReference: string | null; financialNote: string | null; financialCheckedAt: string | null };
type Row = { request: Request; storeName: string; storeSlug: string };

export function HomeExposureRequestReviewPanel({ initialRows }: { initialRows: Row[] }) {
  const [rows, setRows] = useState(initialRows); const [loading, setLoading] = useState<string | null>(null); const [message, setMessage] = useState<string | null>(null);
  async function action(body: Record<string, unknown>, key: string) {
    setLoading(key); setMessage(null);
    try {
      const response = await fetch("/api/admin/home-exposure-requests", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) });
      const json = await response.json().catch(() => ({})); if (!response.ok) throw new Error(json.message || "تعذر تنفيذ العملية");
      setMessage(json.message || "تم الحفظ");
      if (json.data?.request) setRows((current) => current.map((row) => row.request.id === json.data.request.id ? { ...row, request: json.data.request } : row));
      return true;
    } catch (error) { setMessage(error instanceof Error ? error.message : "تعذر تنفيذ العملية"); return false; } finally { setLoading(null); }
  }
  return <section className="rounded-3xl border bg-white p-6 shadow-card"><div className="mb-5"><h2 className="text-2xl font-black">طلبات التجار للظهور المدفوع</h2><p className="mt-2 text-sm leading-7 text-slate-500">وقت وموضع التاجر اقتراح فقط. لا تتحول الحملة إلى إعلان إلا بعد اختيار الإدارة للموضع والتاريخ والساعات النهائية صراحةً.</p></div>{!rows.length ? <p className="rounded-2xl border border-dashed p-7 text-center text-sm font-bold text-slate-500">لا توجد طلبات.</p> : <div className="space-y-4">{rows.map((row) => <RequestCard key={row.request.id} row={row} action={action} loading={loading}/>)}</div>}{message ? <p className="mt-4 rounded-2xl bg-slate-950 p-4 text-sm font-bold text-white">{message}</p> : null}</section>;
}

function RequestCard({ row, action, loading }: { row: Row; action: (body: Record<string, unknown>, key: string) => Promise<boolean>; loading: string | null }) {
  const request = row.request; const terminal = ["approved_pending_activation", "rejected", "cancelled"].includes(request.status);
  const [quote, setQuote] = useState(request.quotedAmount || ""); const [note, setNote] = useState(request.adminNote || ""); const [financialReference, setFinancialReference] = useState(request.financialReference || ""); const [financialNote, setFinancialNote] = useState(request.financialNote || "");
  const [finalPlacement, setFinalPlacement] = useState(request.approvedPlacementId || request.placementId);
  const [finalStartsAt, setFinalStartsAt] = useState(toLocal(request.approvedStartsAt || request.requestedStartsAt));
  const [finalEndsAt, setFinalEndsAt] = useState(toLocal(request.approvedEndsAt || request.requestedEndsAt));
  const initialSchedule = request.approvedVisibilitySchedule?.mode ? request.approvedVisibilitySchedule : request.visibilitySchedule || {};
  const [scheduleMode, setScheduleMode] = useState(initialSchedule.mode || "always"); const [startTime, setStartTime] = useState(initialSchedule.startTime || ""); const [endTime, setEndTime] = useState(initialSchedule.endTime || ""); const [weekDays, setWeekDays] = useState<number[]>(initialSchedule.weekDays || []);
  const canCreate = !terminal && Number(quote) > 0 && Boolean(finalPlacement && finalStartsAt && finalEndsAt);
  const finalSchedule = { mode: scheduleMode, timezone: "Asia/Aden", startTime: startTime || null, endTime: endTime || null, weekDays };
  async function submitQuote(event: FormEvent) { event.preventDefault(); await action({ action: "quote", requestId: request.id, quotedAmount: Number(quote), currency: request.currency || "YER", adminNote: note }, `quote:${request.id}`); }
  async function approve() { await action({ action: "approve_create_campaign", requestId: request.id, quotedAmount: Number(quote), currency: request.currency || "YER", adminNote: note, placementId: finalPlacement, startsAt: toIso(finalStartsAt), endsAt: toIso(finalEndsAt), visibilitySchedule: finalSchedule, config: { manualPriority: 0, rotationWeight: 1, impressionCap: 0, clickCap: 0, paidPriority: true } }, `approve:${request.id}`); }
  async function reject() { await action({ action: "reject", requestId: request.id, adminNote: note || "تم رفض الطلب" }, `reject:${request.id}`); }
  async function recordFinancialCheckpoint(financialCheckpointStatus: "invoice_issued" | "payment_verified") { await action({ action: "record_financial_checkpoint", requestId: request.id, financialCheckpointStatus, financialReference, financialNote }, `financial:${request.id}:${financialCheckpointStatus}`); }
  return <article className="rounded-3xl border bg-slate-50 p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex flex-wrap items-center gap-2"><h3 className="font-black text-slate-950">{row.storeName}</h3><Badge variant={request.status === "approved_pending_activation" ? "warning" : request.status === "rejected" ? "danger" : request.status === "quoted" ? "success" : "outline"}>{statusLabel(request.status)}</Badge></div><p className="mt-1 text-sm font-bold text-slate-600">طلب: {placementLabel(request.placementId)} · {request.commercialModel.toUpperCase()} · الهدف: {request.targetType}</p></div>{request.campaignId ? <span className="rounded-full bg-amber-100 px-3 py-2 text-xs font-black text-amber-900">حملة منشأة بانتظار التفعيل</span> : null}</div>
    <div className="mt-4 grid gap-3 lg:grid-cols-2"><ProposalCard title="اقتراح التاجر — غير ملزم" placement={request.placementId} startsAt={request.requestedStartsAt} endsAt={request.requestedEndsAt} schedule={request.visibilitySchedule}/><ProposalCard title="قرار الإدارة النهائي" placement={request.approvedPlacementId} startsAt={request.approvedStartsAt} endsAt={request.approvedEndsAt} schedule={request.approvedVisibilitySchedule}/></div>
    {request.creative?.description ? <p className="mt-4 rounded-2xl border bg-white p-3 text-sm leading-6 text-slate-600">{String(request.creative.description)}</p> : null}
    {!terminal ? <><form onSubmit={submitQuote} className="mt-4 grid gap-3 rounded-2xl border bg-white p-4 md:grid-cols-[180px_140px_1fr_auto]"><Field label="السعر المعروض" type="number" value={quote} onChange={setQuote}/><div className="space-y-2"><Label>العملة</Label><Input value={request.currency || "YER"} readOnly/></div><Field label="ملاحظة الإدارة" value={note} onChange={setNote} placeholder="سبب النقل أو شروط التسعير"/><Button disabled={loading === `quote:${request.id}`}><CircleDollarSign className="h-4 w-4"/> حفظ التسعير</Button></form>
      <div className="mt-4 rounded-2xl border-2 border-blue-200 bg-blue-50/60 p-4"><div className="mb-3 flex items-center gap-2 text-blue-950"><CalendarClock className="h-5 w-5"/><h4 className="font-black">قرار الإدارة: الموضع والجدولة النهائية</h4></div><p className="mb-4 text-sm leading-6 text-blue-800">يمكنك تجاهل طلب التاجر بالكامل واختيار وقت/تاريخ/موضع آخر بسبب ازدحام الإعلان أو حجز النافذة. هذه القيم فقط ستنشئ الحملة.</p><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3"><div className="space-y-2"><Label>الموضع النهائي</Label><select value={finalPlacement} onChange={(event) => setFinalPlacement(event.target.value)} className="h-11 w-full rounded-xl border bg-white px-3 text-sm">{placements.map(([id,label]) => <option key={id} value={id}>{label}</option>)}</select></div><Field label="البداية النهائية" type="datetime-local" value={finalStartsAt} onChange={setFinalStartsAt}/><Field label="النهاية النهائية" type="datetime-local" value={finalEndsAt} onChange={setFinalEndsAt}/><div className="space-y-2"><Label>نوع الجدولة النهائي</Label><select value={scheduleMode} onChange={(event) => setScheduleMode(event.target.value)} className="h-11 w-full rounded-xl border bg-white px-3 text-sm"><option value="always">دائم ضمن الفترة</option><option value="daily_window">يومياً ضمن ساعات</option><option value="weekly_window">أيام أسبوعية</option><option value="monthly_first_week">أول أسبوع من الشهر</option></select></div><Field label="من الساعة" type="time" value={startTime} onChange={setStartTime}/><Field label="إلى الساعة" type="time" value={endTime} onChange={setEndTime}/><div className="md:col-span-2 xl:col-span-3"><Label>أيام الأسبوع عند اختيار الجدولة الأسبوعية</Label><div className="mt-2 flex flex-wrap gap-2">{days.map(([day,label]) => <label key={day} className="rounded-full border bg-white px-3 py-2 text-xs font-black"><input type="checkbox" checked={weekDays.includes(day)} onChange={(event) => setWeekDays(event.target.checked ? [...weekDays, day] : weekDays.filter((item) => item !== day))}/> {label}</label>)}</div></div></div></div>
      <div className="mt-3 flex flex-wrap gap-2"><Button type="button" variant="secondary" disabled={!canCreate || loading === `approve:${request.id}`} onClick={approve}>{loading === `approve:${request.id}` ? <Loader2 className="h-4 w-4 animate-spin"/> : <CheckCircle2 className="h-4 w-4"/>} اعتماد القرار وإنشاء حملة متوقفة</Button><Button type="button" variant="destructive" disabled={loading === `reject:${request.id}`} onClick={reject}><XCircle className="h-4 w-4"/> رفض</Button></div></> : null}
    {request.status === "approved_pending_activation" ? <div className="mt-4 rounded-2xl border border-amber-200 bg-amber-50 p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="font-black text-amber-950">نقطة القرار المالي قبل التفعيل</p><p className="mt-1 text-sm text-amber-900">الحالة: {financialStatusLabel(request.financialCheckpointStatus)}</p></div><Badge variant={request.financialCheckpointStatus === "payment_verified" ? "success" : request.financialCheckpointStatus === "invoice_issued" ? "warning" : "outline"}>{request.financialCheckpointStatus}</Badge></div><p className="mt-3 text-sm leading-6 text-amber-950">لا يكفي إنشاء الاستحقاق. سجّل إصدار الفاتورة أو مراجعة السداد، ثم فعّل الحملة يدوياً من محرك الظهور وفق قرار الإدارة.</p><div className="mt-3 grid gap-3 md:grid-cols-[1fr_1fr_auto_auto]"><Field label="مرجع الفاتورة/المراجعة" value={financialReference} onChange={setFinancialReference} placeholder="رقم فاتورة أو مرجع تحقق"/><Field label="ملاحظة مالية" value={financialNote} onChange={setFinancialNote} placeholder="لا تعد دليلاً تلقائياً على التحصيل"/><Button type="button" variant="outline" disabled={!financialReference || request.financialCheckpointStatus === "payment_verified" || loading?.startsWith(`financial:${request.id}`)} onClick={() => recordFinancialCheckpoint("invoice_issued")}>تسجيل فاتورة صادرة</Button><Button type="button" variant="secondary" disabled={!financialReference || request.financialCheckpointStatus !== "invoice_issued" || loading?.startsWith(`financial:${request.id}`)} onClick={() => recordFinancialCheckpoint("payment_verified")}>{loading?.startsWith(`financial:${request.id}`) ? <Loader2 className="h-4 w-4 animate-spin"/> : null} تأكيد مراجعة السداد</Button></div>{request.financialCheckedAt ? <p className="mt-3 text-xs font-bold text-amber-800">آخر قرار مالي: {formatDate(request.financialCheckedAt)}</p> : null}</div> : null}
  </article>;
}
function ProposalCard({title,placement,startsAt,endsAt,schedule}:{title:string;placement:string|null;startsAt:string|null;endsAt:string|null;schedule:Schedule}){return <div className="rounded-2xl border bg-white p-4"><p className="text-xs font-black text-slate-500">{title}</p><p className="mt-2 font-black text-slate-950">{placement?placementLabel(placement):"لم يحدد بعد"}</p><p className="mt-2 text-xs leading-6 text-slate-600">{startsAt?formatDate(startsAt):"—"} ← {endsAt?formatDate(endsAt):"—"}<br/>الجدولة: {scheduleLabel(schedule)}</p></div>}
function Field({label,type="text",value,onChange,placeholder}:{label:string;type?:string;value:string;onChange:(value:string)=>void;placeholder?:string}){return <div className="space-y-2"><Label>{label}</Label><Input type={type} value={value} onChange={(event)=>onChange(event.target.value)} placeholder={placeholder}/></div>}
function placementLabel(value:string){return placements.find(([id])=>id===value)?.[1]||value}
function statusLabel(value:string){return ({submitted:"مرسل",quoted:"مسعّر",approved_pending_activation:"بانتظار التفعيل",rejected:"مرفوض",cancelled:"ملغى"} as Record<string,string>)[value]||value}
function financialStatusLabel(value:string){return ({awaiting_invoice:"بانتظار إصدار/تسجيل فاتورة",invoice_issued:"تم تسجيل فاتورة صادرة",payment_verified:"تم تسجيل مراجعة السداد"} as Record<string,string>)[value]||value}
function scheduleLabel(schedule:Schedule){return ({always:"دائم",daily_window:"يومي",weekly_window:"أسبوعي",monthly_first_week:"أول أسبوع شهري"} as Record<string,string>)[schedule?.mode||"always"]||"مخصص"}
function formatDate(value:string){return new Intl.DateTimeFormat("ar",{dateStyle:"medium",timeStyle:"short"}).format(new Date(value))}
function toLocal(value:string|null){if(!value)return "";const date=new Date(value);const offset=date.getTimezoneOffset();return new Date(date.getTime()-offset*60_000).toISOString().slice(0,16)}
function toIso(value:string){return value?new Date(value).toISOString():null}
