"use client";

import { useState, type FormEvent } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";

type Item = { id: string; menuKey: string; title: string; url: string; target: string; isVisible: boolean; sortOrder: number };
export function MenuBuilderPanel({ initialItems }: { initialItems: Item[] }) {
  const router = useRouter(); const [message, setMessage] = useState<string | null>(null); const [loading, setLoading] = useState<string | null>(null);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); setLoading("create"); const response = await fetch("/api/admin/menu-items", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ menuKey: form.get("menuKey") || "main", title: form.get("title"), url: form.get("url"), target: form.get("target"), sortOrder: Number(form.get("sortOrder") || 0), isVisible: true }) }); const json = await response.json().catch(() => ({})); setLoading(null); setMessage(response.ok ? "✓ تم إضافة عنصر القائمة وسيظهر في الهيدر العام إذا كان مرئيًا." : json.message || "تعذر الحفظ"); if (response.ok) { event.currentTarget.reset(); router.refresh(); } }
  async function toggle(item: Item) { setLoading(item.id); const response = await fetch("/api/admin/menu-items", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id: item.id, isVisible: !item.isVisible }) }); const json = await response.json().catch(() => ({})); setLoading(null); setMessage(response.ok ? "✓ تم تحديث ظهور عنصر القائمة" : json.message || "تعذر التحديث"); if (response.ok) router.refresh(); }
  async function remove(id: string) { if (!window.confirm("هل تريد حذف عنصر القائمة؟")) return; setLoading(id); const response = await fetch(`/api/admin/menu-items?id=${id}`, { method: "DELETE" }); const json = await response.json().catch(() => ({})); setLoading(null); setMessage(response.ok ? "✓ تم حذف عنصر القائمة" : json.message || "تعذر الحذف"); if (response.ok) router.refresh(); }
  return <div className="space-y-6">{message ? <p className="rounded-2xl border bg-white p-4 text-sm font-bold text-slate-700">{message}</p> : null}<form onSubmit={submit} className="grid gap-3 rounded-[2rem] border bg-white p-6 shadow-card md:grid-cols-5"><label className="space-y-2"><Label>Menu Key</Label><Input name="menuKey" defaultValue="main"/></label><label className="space-y-2"><Label>العنوان</Label><Input name="title" required/></label><label className="space-y-2"><Label>الرابط</Label><Input name="url" placeholder="/offers" required/></label><label className="space-y-2"><Label>الترتيب</Label><Input name="sortOrder" type="number" defaultValue={0}/></label><label className="space-y-2"><Label>الهدف</Label><select name="target" className="h-11 w-full rounded-xl border bg-white px-3 text-sm"><option value="_self">نفس الصفحة</option><option value="_blank">نافذة جديدة</option></select></label><Button disabled={loading === "create"} className="md:col-span-5">إضافة للقائمة العامة</Button></form><section className="rounded-[2rem] border bg-white p-6 shadow-card"><h2 className="mb-4 text-xl font-black">العناصر الحالية</h2><div className="space-y-2">{initialItems.map((item) => <div key={item.id} className="flex flex-wrap items-center justify-between gap-3 rounded-2xl bg-slate-50 p-4"><div><p className="font-black">{item.title} <span className="text-xs text-slate-500">{item.url}</span></p><p className="mt-1 text-xs text-slate-500">{item.menuKey} · ترتيب {item.sortOrder} · {item.target}</p></div><div className="flex items-center gap-2"><Badge variant={item.isVisible ? "success" : "outline"}>{item.isVisible ? "ظاهر" : "مخفي"}</Badge><Button size="sm" variant="outline" disabled={loading === item.id} onClick={() => void toggle(item)}>{item.isVisible ? "إخفاء" : "إظهار"}</Button><Button size="sm" variant="destructive" disabled={loading === item.id} onClick={() => void remove(item.id)}>حذف</Button></div></div>)}{!initialItems.length ? <p className="rounded-2xl bg-slate-50 p-4 text-sm font-bold text-slate-500">لا توجد عناصر؛ سيبقى الهيدر الأساسي دون روابط مخصصة.</p> : null}</div></section></div>;
}
