"use client";
import { useState, type FormEvent } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { MediaUrlInput } from "@/components/media/media-url-input";
export function OfferCampaignForm(){const router=useRouter();const[message,setMessage]=useState<string|null>(null);async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const f=new FormData(form);const res=await fetch('/api/admin/offer-campaigns',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:f.get('name'),slug:f.get('slug')||undefined,occasionType:f.get('occasionType')||'seasonal',description:f.get('description')||undefined,imageUrl:f.get('imageUrl')||'',startAt:f.get('startAt')?new Date(String(f.get('startAt'))).toISOString():null,endAt:f.get('endAt')?new Date(String(f.get('endAt'))).toISOString():null,status:f.get('status'),isHomepageVisible:f.get('isHomepageVisible')==='on',sortOrder:Number(f.get('sortOrder')||0)})});const data=await res.json();setMessage(res.ok?'✓ تم إنشاء موسم العروض':data.message||'تعذر الحفظ');if(res.ok){form.reset();router.refresh();}}return <form onSubmit={submit} className="grid gap-4 rounded-3xl border bg-white p-6 shadow-card md:grid-cols-2"><div className="space-y-2"><Label>اسم المناسبة</Label><Input name="name" required placeholder="رمضان / عيد الفطر / بداية السنة"/></div><div className="space-y-2"><Label>slug</Label><Input name="slug"/></div><div className="space-y-2"><Label>نوع المناسبة</Label><Input name="occasionType" placeholder="ramadan / eid / new-year"/></div><MediaUrlInput label="صورة المناسبة: رابط أو رفع" name="imageUrl" folder="admin/offer-campaigns" accept="image/*"/><div className="space-y-2"><Label>تاريخ البداية</Label><Input name="startAt" type="datetime-local"/></div><div className="space-y-2"><Label>تاريخ النهاية</Label><Input name="endAt" type="datetime-local"/></div><div className="space-y-2"><Label>الحالة</Label><select name="status" className="h-11 w-full rounded-xl border px-4"><option value="active">نشط</option><option value="draft">مسودة</option><option value="disabled">معطل</option></select></div><div className="space-y-2"><Label>الترتيب</Label><Input name="sortOrder" type="number"/></div><label className="flex items-center gap-2 font-bold"><input name="isHomepageVisible" type="checkbox" defaultChecked/> يظهر في الرئيسية</label><div className="space-y-2 md:col-span-2"><Label>الوصف</Label><Textarea name="description"/></div><div className="md:col-span-2 flex items-center gap-3"><Button>حفظ المناسبة</Button>{message?<span className="text-sm font-bold text-slate-600">{message}</span>:null}</div></form>}
