"use client";

import { FormEvent, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { ActionConfirmationDialog } from "@/components/ui/action-confirmation-dialog";
import { apiClient, ApiClientError } from "@/lib/client/api-client";
import { formatCurrency } from "@/lib/utils";

type Store = { id: string; name: string; storeNumber: string; merchantId: string };
type Props = { stores: Store[]; terms: any[]; promotionAgreements: any[]; statements: any[]; reports: any[]; outstanding: number };
const periodDefault = () => { const now = new Date(); const start = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth() - 1, 1)); const end = new Date(Date.UTC(now.getUTCFullYear(), now.getUTCMonth(), 1)); return { start: start.toISOString().slice(0, 16), end: end.toISOString().slice(0, 16) }; };
function statusVariant(status: string) { return status === "paid" || status === "approved" || status === "active" ? "success" as const : status === "overdue" || status === "rejected" || status === "suspended" ? "danger" as const : "warning" as const; }

export function PlatformRevenueManagementPanel({ stores, terms, promotionAgreements, statements, reports, outstanding }: Props) {
  const router = useRouter();
  const [message, setMessage] = useState<string | null>(null); const [loading, setLoading] = useState(false);
  const [confirm, setConfirm] = useState<{ kind: "report" | "statement"; id: string; action: string; title: string; description: string } | null>(null);
  const [error, setError] = useState<string | null>(null);
  const defaults = useMemo(periodDefault, []);
  const storeById = useMemo(() => new Map(stores.map((store) => [store.id, store])), [stores]);

  async function saveTerms(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const store = storeById.get(String(form.get("storeId") || "")); if (!store) return; setLoading(true); setMessage(null); try { const data = await apiClient.post<any>("/api/admin/platform-revenue/terms", { storeId: store.id, merchantId: store.merchantId, model: form.get("model"), monthlyRent: Number(form.get("monthlyRent") || 0), commissionRate: Number(form.get("commissionRate") || 0), dueDays: Number(form.get("dueDays") || 7), graceDays: Number(form.get("graceDays") || 7), currency: "YER", status: "active", note: form.get("note") || null }, { invalidateTags: ["platform-revenue"] }); setMessage(data.message || "تم حفظ شروط الإيراد"); event.currentTarget.reset(); router.refresh(); } catch (caught) { setMessage(caught instanceof ApiClientError ? caught.message : "تعذر حفظ الشروط"); } finally { setLoading(false); } }
  async function savePromotion(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const store = storeById.get(String(form.get("storeId") || "")); if (!store) return; setLoading(true); setMessage(null); try { const data = await apiClient.post<any>("/api/admin/platform-revenue/promotion-agreements", { storeId: store.id, merchantId: store.merchantId, homepageBannerFee: Number(form.get("homepageBannerFee") || 0), featuredProductFee: Number(form.get("featuredProductFee") || 0), featuredStoreFee: Number(form.get("featuredStoreFee") || 0), currency: "YER", status: "active", note: form.get("note") || null }, { invalidateTags: ["platform-revenue", "admin:ads"] }); setMessage(data.message || "تم حفظ اتفاق الترويج"); event.currentTarget.reset(); router.refresh(); } catch (caught) { setMessage(caught instanceof ApiClientError ? caught.message : "تعذر حفظ الاتفاق"); } finally { setLoading(false); } }
  async function issueStatement(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); setLoading(true); setMessage(null); try { const data = await apiClient.post<any>("/api/admin/platform-revenue/statements", { storeId: form.get("storeId"), periodStart: new Date(String(form.get("periodStart"))).toISOString(), periodEnd: new Date(String(form.get("periodEnd"))).toISOString() }, { invalidateTags: ["platform-revenue"] }); setMessage(data.message || "تمت معالجة الكشف"); router.refresh(); } catch (caught) { setMessage(caught instanceof ApiClientError ? caught.message : "تعذر إصدار الكشف"); } finally { setLoading(false); } }
  async function executeConfirmed(reason: string) { if (!confirm) return; setLoading(true); setError(null); try { if (confirm.kind === "report") await apiClient.patch(`/api/admin/platform-revenue/sales-reports/${confirm.id}`, { action: confirm.action, note: reason }, { invalidateTags: ["platform-revenue"] }); else await apiClient.patch("/api/admin/platform-revenue/statements", { statementId: confirm.id, action: confirm.action, note: reason }, { invalidateTags: ["platform-revenue"] }); setConfirm(null); router.refresh(); } catch (caught) { setError(caught instanceof ApiClientError ? caught.message : "تعذر تنفيذ العملية"); } finally { setLoading(false); } }
  const select = (name: string) => <select name={name} required className="h-11 w-full rounded-xl border bg-white px-3 text-sm"><option value="">اختر المتجر</option>{stores.map((store) => <option key={store.id} value={store.id}>{store.name} — {store.storeNumber}</option>)}</select>;

  return <div className="space-y-8">{message ? <p className="rounded-2xl border bg-white p-4 text-sm font-bold text-slate-700">{message}</p> : null}<section className="grid gap-4 lg:grid-cols-3"><Metric label="كشوف مستحقة" value={formatCurrency(outstanding)} /><Metric label="شروط إيراد مفعلة" value={terms.filter((row:any)=>row.terms.status === "active").length} /><Metric label="تقارير مبيعات تنتظر" value={reports.filter((row:any)=>row.report.status === "submitted").length} /></section>
    <section className="grid gap-6 xl:grid-cols-2"><form onSubmit={saveTerms} className="grid gap-3 rounded-3xl border bg-white p-6 shadow-card md:grid-cols-2"><div className="md:col-span-2"><h2 className="text-xl font-black">1. نموذج إيراد المنصة للتاجر</h2><p className="mt-1 text-xs leading-6 text-slate-500">هذا العقد المالي يحدد فقط إيجار المنصة وعمولتها؛ لا يلمس أي دفعة عميل أو رصيد تاجر.</p></div><Field label="المتجر">{select("storeId")}</Field><Field label="النموذج"><select name="model" className="h-11 w-full rounded-xl border bg-white px-3 text-sm"><option value="monthly_rent">إيجار شهري فقط</option><option value="sales_commission">نسبة مبيعات فقط</option><option value="hybrid">إيجار + نسبة مبيعات</option></select></Field><Field label="الإيجار الشهري (ريال)"><Input name="monthlyRent" type="number" min="0" defaultValue="0" /></Field><Field label="نسبة العمولة %"><Input name="commissionRate" type="number" min="0" max="100" step="0.001" defaultValue="0" /></Field><Field label="أيام الاستحقاق"><Input name="dueDays" type="number" min="1" max="90" defaultValue="7" /></Field><Field label="أيام السماح قبل التعليق"><Input name="graceDays" type="number" min="0" max="90" defaultValue="7" /></Field><div className="md:col-span-2"><Label>ملاحظة تعاقدية</Label><Textarea name="note" className="mt-2" placeholder="سبب أو مرجع اعتماد النموذج المالي" /></div><Button disabled={loading} className="md:col-span-2">حفظ وتفعيل الفوترة الموحدة</Button></form>
      <form onSubmit={savePromotion} className="grid gap-3 rounded-3xl border bg-white p-6 shadow-card md:grid-cols-2"><div className="md:col-span-2"><h2 className="text-xl font-black">2. اتفاق الترويج والإعلانات المستقل</h2><p className="mt-1 text-xs leading-6 text-slate-500">رسوم الظهور في الواجهة لا تدخل عقد الإيجار، لكنها تضاف لاحقاً كسطر منفصل داخل كشف المنصة الموحد.</p></div><Field label="المتجر">{select("storeId")}</Field><Field label="رسوم بنر الرئيسية"><Input name="homepageBannerFee" type="number" min="0" defaultValue="0" /></Field><Field label="رسوم منتج مميز بالرئيسية"><Input name="featuredProductFee" type="number" min="0" defaultValue="0" /></Field><Field label="رسوم متجر مميز"><Input name="featuredStoreFee" type="number" min="0" defaultValue="0" /></Field><div className="md:col-span-2"><Label>ملاحظة اتفاق الترويج</Label><Textarea name="note" className="mt-2" placeholder="مثال: العرض لمدة شهر أو حسب الحملة" /></div><Button disabled={loading} variant="outline" className="md:col-span-2">حفظ اتفاق الترويج</Button></form></section>
    <section className="rounded-3xl border bg-white p-6 shadow-card"><h2 className="text-xl font-black">3. إصدار كشف موحد لفترة</h2><form onSubmit={issueStatement} className="mt-4 grid gap-3 md:grid-cols-4"><div>{select("storeId")}</div><Field label="بداية الفترة"><Input name="periodStart" type="datetime-local" defaultValue={defaults.start} /></Field><Field label="نهاية الفترة"><Input name="periodEnd" type="datetime-local" defaultValue={defaults.end} /></Field><Button disabled={loading} className="self-end">إنشاء/تحديث الكشف</Button></form></section>
    <section className="rounded-3xl border bg-white p-6 shadow-card"><h2 className="text-xl font-black">تقارير المبيعات بانتظار المراجعة</h2>{!reports.length ? <Empty text="لا توجد تقارير." /> : <div className="mt-4 overflow-x-auto"><table className="w-full min-w-[850px] text-right text-sm"><thead className="bg-slate-100"><tr><th className="p-3">المتجر</th><th className="p-3">الفترة</th><th className="p-3">المبيعات</th><th className="p-3">الحالة</th><th className="p-3">البنود</th><th className="p-3">إجراء</th></tr></thead><tbody>{reports.map((row:any)=><tr key={row.report.id} className="border-t"><td className="p-3 font-black">{row.storeName}</td><td className="p-3">{date(row.report.periodStart)} — {date(row.report.periodEnd)}</td><td className="p-3">{formatCurrency(row.report.salesTotal,row.report.currency)}</td><td className="p-3"><Badge variant={statusVariant(row.report.status)}>{row.report.status}</Badge></td><td className="p-3">{row.report.status === "submitted" ? <div className="flex gap-2"><Button size="sm" onClick={()=>setConfirm({kind:"report",id:row.report.id,action:"approve",title:"اعتماد تقرير المبيعات",description:"سيستخدم إجمالي المبيعات المعتمد لحساب عمولة المنصة وإصدار/تحديث الكشف الشهري."})}>اعتماد</Button><Button size="sm" variant="destructive" onClick={()=>setConfirm({kind:"report",id:row.report.id,action:"reject",title:"رفض تقرير المبيعات",description:"سيبقى كشف الفترة بانتظار تقرير مبيعات صحيح ومعتمد."})}>رفض</Button></div>:"-"}</td></tr>)}</tbody></table></div>}</section>
    <section className="rounded-3xl border bg-white p-6 shadow-card"><h2 className="text-xl font-black">الكشف الشهري الموحد</h2><p className="mt-1 text-xs text-slate-500">يجمع الإيجار والعمولة والإعلانات والإضافات. لا يحتوي مبيعات العملاء ولا يحول أموالاً للتاجر.</p>{!statements.length?<Empty text="لا توجد كشوف بعد."/>:<div className="mt-4 overflow-x-auto"><table className="w-full min-w-[1100px] text-right text-sm"><thead className="bg-slate-100"><tr><th className="p-3">الرقم/المتجر</th><th className="p-3">الفترة</th><th className="p-3">إيجار</th><th className="p-3">عمولة</th><th className="p-3">إعلانات</th><th className="p-3">الإجمالي</th><th className="p-3">الحالة</th><th className="p-3">البنود</th><th className="p-3">إجراء</th></tr></thead><tbody>{statements.map((row:any)=><tr key={row.statement.id} className="border-t"><td className="p-3 font-black">{row.statement.statementNumber}<div className="text-xs font-normal text-slate-500">{row.storeName}</div></td><td className="p-3">{date(row.statement.periodStart)} — {date(row.statement.periodEnd)}</td><td className="p-3">{formatCurrency(row.statement.rentAmount,row.statement.currency)}</td><td className="p-3">{formatCurrency(row.statement.commissionAmount,row.statement.currency)}</td><td className="p-3">{formatCurrency(row.statement.advertisingAmount,row.statement.currency)}</td><td className="p-3 font-black text-primary">{formatCurrency(row.statement.totalAmount,row.statement.currency)}</td><td className="p-3"><Badge variant={statusVariant(row.statement.status)}>{row.statement.status}</Badge></td><td className="p-3"><details><summary className="cursor-pointer text-xs font-black text-primary">عرض البنود ({row.lines?.length || 0})</summary><ul className="mt-2 space-y-1 text-xs text-slate-600">{(row.lines || []).map((line:any)=><li key={line.id}>{line.description}: {formatCurrency(line.totalAmount,row.statement.currency)}</li>)}</ul></details></td><td className="p-3">{["issued","overdue","payment_submitted"].includes(row.statement.status)?<div className="flex gap-2"><Button size="sm" onClick={()=>setConfirm({kind:"statement",id:row.statement.id,action:row.statement.status === "payment_submitted"?"approve_proof":"mark_paid",title:"تأكيد سداد كشف المنصة",description:"هذا تأكيد إداري لتحصيل إيراد المنصة فقط؛ لا يؤثر في دفعات العملاء للتاجر."})}>تأكيد سداد</Button><Button size="sm" variant="destructive" onClick={()=>setConfirm({kind:"statement",id:row.statement.id,action:"void",title:"إلغاء كشف المنصة",description:"سيحتفظ النظام بالسجل ويعيد فواتير الإعلانات المرتبطة إلى حالتها القابلة للمراجعة."})}>إلغاء</Button></div>:"-"}</td></tr>)}</tbody></table></div>}</section>
    <ActionConfirmationDialog open={Boolean(confirm)} title={confirm?.title || ""} description={confirm?.description || ""} actionLabel="تأكيد" destructive={confirm?.action === "void" || confirm?.action === "reject"} reasonRequired auditContext={confirm?.kind === "report" ? "merchant_sales_report" : "platform_revenue_statement"} loading={loading} error={error} onClose={()=>{if(!loading){setConfirm(null);setError(null);}}} onConfirm={({reason})=>executeConfirmed(reason)} />
  </div>;
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="space-y-2 text-sm font-black text-slate-700"><span>{label}</span>{children}</label>;}
function Metric({label,value}:{label:string;value:string|number}){return <article className="rounded-3xl border bg-white p-5 shadow-card"><p className="text-sm font-bold text-slate-500">{label}</p><p className="mt-2 text-2xl font-black text-slate-950">{value}</p></article>;}
function Empty({text}:{text:string}){return <p className="mt-4 rounded-2xl border border-dashed bg-slate-50 p-5 text-sm font-bold text-slate-500">{text}</p>;}
function date(value:string|Date){return new Intl.DateTimeFormat("ar",{dateStyle:"short"}).format(new Date(value));}
