"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";

type Readiness = { score: number; dangerCount: number; warnCount: number; checks: Array<{ ok: boolean; label: string; description: string; severity: string }> };
type Drill = { id: string; kind: string; environment: string; status: string; createdAt: string | Date; note: string | null };
type Gate = { id: string; environment: string; status: string; readinessScore: number | null; createdAt: string | Date };

export function ReleaseGatePanel({ readiness, drills, gates }: { readiness: Readiness; drills: Drill[]; gates: Gate[] }) {
  const router = useRouter(); const [message, setMessage] = useState<string | null>(null);
  async function post(body: Record<string, unknown>) { const response = await fetch("/api/admin/operations/release-gates", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const json = await response.json().catch(() => ({})); setMessage(response.ok ? json.data?.message || "تم الحفظ" : json.message || "تعذر الحفظ"); if (response.ok) router.refresh(); }
  const failed = readiness.checks.filter((check) => !check.ok);
  return <div className="space-y-6"><section className="rounded-3xl border bg-white p-6 shadow-card"><div className="flex flex-wrap items-center justify-between gap-4"><div><h2 className="text-xl font-black">بوابة الإطلاق</h2><p className="mt-1 text-sm text-slate-500">الدليل الآلي لا ينشر النظام؛ يسجل حالة المتطلبات والمخاطر ليوقعها التشغيل بعد اختبارات Staging الحقيقية.</p></div><div className="flex items-center gap-2"><Badge variant={readiness.dangerCount ? "danger" : "success"}>Readiness {readiness.score}%</Badge><Button onClick={() => void post({ action: "record_gate", environment: "staging" })}>حفظ دليل الجاهزية</Button></div></div><div className="mt-5 grid gap-2 md:grid-cols-2">{readiness.checks.map((check) => <div key={check.label} className={`rounded-xl border p-3 text-sm ${check.ok ? "border-emerald-200 bg-emerald-50" : check.severity === "danger" ? "border-red-200 bg-red-50" : "border-amber-200 bg-amber-50"}`}><b>{check.ok ? "✓" : "!"} {check.label}</b><p className="mt-1 text-xs">{check.description}</p></div>)}</div>{failed.length ? <p className="mt-4 text-sm font-bold text-red-700">لا يمكن اعتبار الإنتاج جاهزاً ما دامت عناصر الخطر أعلاه مفتوحة.</p> : null}</section><section className="rounded-3xl border bg-white p-6 shadow-card"><h2 className="text-xl font-black">تسجيل اختبارات التشغيل</h2><p className="mt-1 text-sm text-slate-500">سجل نتيجة Staging E2E، استعادة النسخة، اختبار الضغط، بوابة الأمن وPilot ERP مع الدليل الخارجي.</p><div className="mt-4 flex flex-wrap gap-2">{["staging_e2e", "backup_recovery", "load_probe", "security_gate", "erp_pilot"].map((kind) => <Button key={kind} size="sm" variant="outline" onClick={() => void post({ kind, environment: "staging", status: "passed", evidence: { recordedAt: new Date().toISOString(), operatorMustAttachExternalEvidence: true } })}>تسجيل {kind}</Button>)}</div>{message ? <p className="mt-3 rounded-xl bg-slate-50 p-3 text-sm font-bold">{message}</p> : null}<div className="mt-5 grid gap-2 md:grid-cols-2">{drills.map((drill) => <div key={drill.id} className="rounded-xl border p-3 text-sm"><Badge variant={drill.status === "passed" ? "success" : drill.status === "failed" ? "danger" : "warning"}>{drill.status}</Badge><b className="mr-2">{drill.kind}</b><p className="mt-1 text-xs text-slate-500">{drill.environment} • {new Date(drill.createdAt).toLocaleString("ar")}</p></div>)}</div></section><section className="rounded-3xl border bg-white p-6 shadow-card"><h2 className="text-xl font-black">آخر لقطات بوابة الإطلاق</h2><div className="mt-4 space-y-2">{gates.map((gate) => <div key={gate.id} className="flex justify-between rounded-xl bg-slate-50 p-3 text-sm"><span>{gate.environment} — {new Date(gate.createdAt).toLocaleString("ar")}</span><span><Badge variant={gate.status === "passed" ? "success" : "danger"}>{gate.status}</Badge> <b className="mr-2">{gate.readinessScore ?? 0}%</b></span></div>)}</div></section></div>;
}
