"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { ActionConfirmationDialog } from "@/components/ui/action-confirmation-dialog";
import { apiClient, ApiClientError } from "@/lib/client/api-client";
import { AdminAiLens } from "@/components/admin/admin-ai-lens";
type Row={readiness:any;storeName:string;storeNumber:string;checks:any};
export function StoreLaunchReadinessReviewPanel({rows}:{rows:Row[]}){const router=useRouter();const [target,setTarget]=useState<{row:Row;action:"approve"|"reject"}|null>(null);const [loading,setLoading]=useState(false);const [error,setError]=useState<string|null>(null);async function review(note:string){if(!target)return;setLoading(true);setError(null);try{await apiClient.patch(`/api/admin/stores/${target.row.readiness.storeId}/launch-readiness`,{action:target.action,note},{invalidateTags:["stores","launch"]});setTarget(null);router.refresh()}catch(caught){setError(caught instanceof ApiClientError?caught.message:"تعذر مراجعة الإطلاق")}finally{setLoading(false)}}return <section className="rounded-3xl border bg-white p-6 shadow-card">{!rows.length?<p className="text-sm font-bold text-slate-500">لا توجد متاجر مرسلة لمراجعة الإطلاق.</p>:<div className="space-y-4">{rows.map((row)=><article key={row.readiness.id} className="rounded-2xl border bg-slate-50 p-5"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="font-black text-slate-950">{row.storeName}</h2><p className="mt-1 text-xs text-slate-500">{row.storeNumber}</p></div><Badge variant={row.readiness.status==="submitted"?"warning":"outline"}>{row.readiness.status}</Badge></div><div className="mt-4 grid gap-2 md:grid-cols-3">{Object.entries(row.checks||{}).map(([key,value]:any)=><div key={key} className={`rounded-xl p-3 text-xs font-bold ${value.ok?"bg-emerald-50 text-emerald-800":"bg-white text-slate-600"}`}><b>{value.label}</b><p className="mt-1">{value.ok?"مكتمل":"ناقص"} · {value.detail}</p></div>)}</div><div className="mt-4"><AdminAiLens kind="launch" id={row.readiness.storeId}/></div><div className="mt-4 flex gap-2"><Button size="sm" onClick={()=>setTarget({row,action:"approve"})}>اعتماد ونشر</Button><Button size="sm" variant="destructive" onClick={()=>setTarget({row,action:"reject"})}>إعادة للتهيئة</Button></div></article>)}</div>}<ActionConfirmationDialog open={Boolean(target)} title={target?.action==="approve"?"نشر المتجر للعامة":"إرجاع المتجر للتهيئة"} description={target?.action==="approve"?"سيتحول المتجر من pending إلى active ويظهر للمستخدمين إذا اجتاز الخادم جميع checks الإلزامية.":"سيبقى حساب التاجر فعالاً لكن المتجر لن يظهر للعامة حتى يعالج النواقص ويرسل checklist من جديد."} actionLabel={target?.action==="approve"?"اعتماد الإطلاق":"إعادة للتهيئة"} destructive={target?.action==="reject"} reasonRequired={target?.action==="reject"} auditContext="store_launch_readiness" loading={loading} error={error} onClose={()=>{if(!loading){setTarget(null);setError(null)}}} onConfirm={({reason})=>review(reason)}/></section>}
