"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { ActionConfirmationDialog } from "@/components/ui/action-confirmation-dialog";
import { apiClient,ApiClientError } from "@/lib/client/api-client";
function tone(status:string){return status==="approved"?"success" as const:status==="rejected"?"danger" as const:"warning" as const;}
export function AdminStoreIdentityChangeRequestsPanel({rows}:{rows:any[]}){const router=useRouter();const [target,setTarget]=useState<{row:any;action:"create_addendum"|"reject"|"activate_addendum"}|null>(null);const [loading,setLoading]=useState(false);const [error,setError]=useState<string|null>(null);async function execute(reason:string){if(!target)return;setLoading(true);setError(null);try{await apiClient.patch("/api/admin/store-identity-change-requests",{requestId:target.row.request.id,action:target.action,note:reason},{invalidateTags:["stores","contracts"]});setTarget(null);router.refresh()}catch(caught){setError(caught instanceof ApiClientError?caught.message:"تعذر تحديث الطلب")}finally{setLoading(false)}}return <section className="rounded-3xl border bg-white p-6 shadow-card">{!rows.length?<p className="text-sm font-bold text-slate-500">لا توجد طلبات تعديل هوية متجر.</p>:<div className="space-y-4">{rows.map((row:any)=>{const request=row.request;return <article key={request.id} className="rounded-2xl border bg-slate-50 p-5"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="font-black">{row.storeName} — {row.storeNumber}</h2><p className="mt-1 text-xs text-slate-500">{request.fieldKey}: {request.currentValue?.value||"-"} ← {request.requestedValue?.value||"-"}</p></div><Badge variant={tone(request.status)}>{request.status}</Badge></div><p className="mt-3 text-sm text-slate-600">السبب: {request.reason}</p>{request.adminNote?<p className="mt-2 rounded-xl bg-amber-50 p-3 text-sm font-bold text-amber-800">{request.adminNote}</p>:null}<div className="mt-4 flex flex-wrap gap-2">{request.status==="pending_review"?<><Button size="sm" onClick={()=>setTarget({row,action:"create_addendum"})}>إنشاء ملحق للتوقيع</Button><Button size="sm" variant="destructive" onClick={()=>setTarget({row,action:"reject"})}>رفض</Button></>:null}{request.status==="awaiting_addendum_signature"&&row.addendum?.status==="signed"?<Button size="sm" onClick={()=>setTarget({row,action:"activate_addendum"})}>اعتماد الملحق وتطبيق التعديل</Button>:null}</div></article>})}</div>}<ActionConfirmationDialog open={Boolean(target)} title={target?.action==="create_addendum"?"إنشاء ملحق عقد":target?.action==="activate_addendum"?"تطبيق تعديل بيانات المتجر":"رفض طلب تعديل الهوية"} description={target?.action==="create_addendum"?"سينشأ ملحق بإصدار وبصمة ويرسل للتاجر للتوقيع قبل تطبيق الاسم أو البريد الجديد.":target?.action==="activate_addendum"?"تم توقيع الملحق. سيطبق التعديل المحدد فقط بعد هذا الاعتماد.":"سيحفظ سبب الرفض ويبلغ التاجر."} actionLabel="تأكيد" destructive={target?.action==="reject"} reasonRequired={target?.action!=="activate_addendum"} auditContext="store_identity_change_request" loading={loading} error={error} onClose={()=>{if(!loading){setTarget(null);setError(null)}}} onConfirm={({reason})=>execute(reason)}/></section>}
