export const dynamic = "force-dynamic";

import { eq } from "drizzle-orm";
import { z } from "zod";
import { optionalUrlOrPathSchema, requiredUrlOrPathSchema } from "@/lib/validators";
import { fail, handleApiError, ok } from "@/lib/api";
import { hasStoreAccess, requireAuth } from "@/lib/auth";
import { categories, colors, db, sizes, units } from "@/lib/db";
import { writeAuditLog } from "@/lib/audit";
const schema = z.object({ name: z.string().min(1).optional(), isActive: z.boolean().optional(), sortOrder: z.coerce.number().int().optional(), imageUrl: optionalUrlOrPathSchema, symbol: z.string().optional(), hexCode: z.string().optional() });
async function getStoreId(kind: string, id: string) { if (kind === "categories") return (await db.select({ storeId: categories.storeId }).from(categories).where(eq(categories.id, id)).limit(1))[0]?.storeId; if (kind === "units") return (await db.select({ storeId: units.storeId }).from(units).where(eq(units.id, id)).limit(1))[0]?.storeId; if (kind === "sizes") return (await db.select({ storeId: sizes.storeId }).from(sizes).where(eq(sizes.id, id)).limit(1))[0]?.storeId; if (kind === "colors") return (await db.select({ storeId: colors.storeId }).from(colors).where(eq(colors.id, id)).limit(1))[0]?.storeId; return null; }
export async function PATCH(request: Request, context: { params: Promise<{ kind: string; id: string }> }) {
  const params = await context.params; try { const session = await requireAuth(); const storeId = await getStoreId(params.kind, params.id); if (!storeId) return fail("العنصر غير موجود", 404); if (!hasStoreAccess(session, storeId)) return fail("لا تملك الصلاحية", 403); const payload = schema.parse(await request.json()); let item; if (params.kind === "categories") [item] = await db.update(categories).set({ name: payload.name, imageUrl: payload.imageUrl || undefined, isActive: payload.isActive, sortOrder: payload.sortOrder, updatedAt: new Date() }).where(eq(categories.id, params.id)).returning(); else if (params.kind === "units") [item] = await db.update(units).set({ name: payload.name, symbol: payload.symbol, isActive: payload.isActive, sortOrder: payload.sortOrder }).where(eq(units.id, params.id)).returning(); else if (params.kind === "sizes") [item] = await db.update(sizes).set({ name: payload.name, isActive: payload.isActive, sortOrder: payload.sortOrder }).where(eq(sizes.id, params.id)).returning(); else if (params.kind === "colors") [item] = await db.update(colors).set({ name: payload.name, hexCode: payload.hexCode, isActive: payload.isActive, sortOrder: payload.sortOrder }).where(eq(colors.id, params.id)).returning(); await writeAuditLog({ actorId: session.userId, action: "update", entityType: params.kind, entityId: params.id, afterData: item }); return ok({ item, message: "تم التعديل بنجاح" }); } catch (error) { return handleApiError(error, "تعذر التعديل"); } }
export async function DELETE(_request: Request, context: { params: Promise<{ kind: string; id: string }> }) {
  const params = await context.params; try { const session = await requireAuth(); const storeId = await getStoreId(params.kind, params.id); if (!storeId) return fail("العنصر غير موجود", 404); if (!hasStoreAccess(session, storeId)) return fail("لا تملك الصلاحية", 403); let item; if (params.kind === "categories") [item] = await db.update(categories).set({ isActive: false, updatedAt: new Date() }).where(eq(categories.id, params.id)).returning(); else if (params.kind === "units") [item] = await db.update(units).set({ isActive: false }).where(eq(units.id, params.id)).returning(); else if (params.kind === "sizes") [item] = await db.update(sizes).set({ isActive: false }).where(eq(sizes.id, params.id)).returning(); else if (params.kind === "colors") [item] = await db.update(colors).set({ isActive: false }).where(eq(colors.id, params.id)).returning(); await writeAuditLog({ actorId: session.userId, action: "delete", entityType: params.kind, entityId: params.id, afterData: item }); return ok({ message: "تم تعطيل العنصر بنجاح" }); } catch (error) { return handleApiError(error, "تعذر تعطيل العنصر"); } }
